/**
 * Tool comparison data — shows how ToolboxPro compares to alternatives.
 * Each tool can have 1-2 competitor comparisons.
 * Renders on tool pages for SEO value and user decision-making.
 */

export interface ToolComparison {
  toolName: string;
  toolNameZh: string;
  competitors: {
    name: string;
    url: string;
    pros: string[];
    prosZh: string[];
    cons: string[];
    consZh: string[];
  }[];
  toolboxProAdvantages: string[];
  toolboxProAdvantagesZh: string[];
}


const comparisons: Record<string, ToolComparison> = {
  "json-formatter": {
    toolName: "JSON Formatter & Validator",
    toolNameZh: "JSON 格式化工具",
    competitors: [
      {
        name: "JSONLint",
        url: "https://jsonlint.com",
        pros: ["Simple interface", "Quick validation"],
        prosZh: ["界面简洁", "快速验证"],
        cons: ["No tree view", "No minification option", "Shows ads"],
        consZh: ["无树状视图", "无压缩功能", "有广告"],
      },
      {
        name: "VS Code Built-in",
        url: "https://code.visualstudio.com",
        pros: ["Integrated in editor", "Extension support"],
        prosZh: ["编辑器集成", "插件支持"],
        cons: ["Requires software installation", "Not browser-based"],
        consZh: ["需安装软件", "非浏览器端"],
      },
    ],
    toolboxProAdvantages: [
      "Tree view for exploring nested JSON",
      "Format, validate, and minify in one tool",
      "No ads, no signup, completely free",
      "Works on mobile browsers",
    ],
    toolboxProAdvantagesZh: [
      "树状视图探索嵌套JSON",
      "格式化、验证和压缩一体化",
      "无广告、无注册、完全免费",
      "移动端浏览器可用",
    ],
  },
  "image-compressor": {
    toolName: "Image Compressor",
    toolNameZh: "图片压缩",
    competitors: [
      {
        name: "TinyPNG",
        url: "https://tinypng.com",
        pros: ["High quality compression", "Batch support"],
        prosZh: ["高质量压缩", "批量处理"],
        cons: ["5 MB file limit on free tier", "Uploads files to server", "Requires email for large batches"],
        consZh: ["免费版限 5MB", "文件上传服务器", "大批量需邮箱"],
      },
      {
        name: "Squoosh",
        url: "https://squoosh.app",
        pros: ["Google-made", "Side-by-side preview"],
        prosZh: ["Google 出品", "并排预览"],
        cons: ["Single file at a time", "No batch processing", "Complex interface"],
        consZh: ["单文件处理", "无批量处理", "界面复杂"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limit (browser memory permitting)",
      "Files never leave your device",
      "Batch compression for multiple files",
      "Supports JPEG, PNG, and WebP",
    ],
    toolboxProAdvantagesZh: [
      "无文件大小限制(受内存限制)",
      "文件从不离开您的设备",
      "支持多文件批量压缩",
      "支持 JPEG、PNG 和 WebP",
    ],
  },
  "pdf-merger": {
    toolName: "PDF Merger",
    toolNameZh: "PDF 合并",
    competitors: [
      {
        name: "ILovePDF",
        url: "https://ilovepdf.com",
        pros: ["Many PDF tools", "Clean interface"],
        prosZh: ["PDF 工具丰富", "界面清爽"],
        cons: ["File size limits on free tier", "Uploads files to server", "Daily usage limits"],
        consZh: ["免费版有大小限制", "文件上传服务器", "每日用量限制"],
      },
      {
        name: "Smallpdf",
        url: "https://smallpdf.com",
        pros: ["All-in-one platform", "Cloud integration"],
        prosZh: ["一站式平台", "云集成"],
        cons: ["2 free tasks/day limit", "Requires account for full features", "Server-side processing"],
        consZh: ["每天仅 2 次免费", "完整功能需注册", "服务器端处理"],
      },
    ],
    toolboxProAdvantages: [
      "No usage limits — unlimited merges",
      "Files stay on your device (100% private)",
      "No account required",
      "Drag-and-drop page reordering",
    ],
    toolboxProAdvantagesZh: [
      "无使用限制，无限合并",
      "文件保留在本地，100%私密",
      "无需注册账户",
      "拖拽排序页面",
    ],
  },
  "password-generator": {
    toolName: "Password Generator",
    toolNameZh: "密码生成器",
    competitors: [
      {
        name: "LastPass Generator",
        url: "https://lastpass.com",
        pros: ["Integrated with password manager", "Auto-save"],
        prosZh: ["密码管理器集成", "自动保存"],
        cons: ["Requires account", "Proprietary", "Cloud-stored"],
        consZh: ["需要注册", "闭源", "云端存储"],
      },
      {
        name: "Norton Password Generator",
        url: "https://norton.com",
        pros: ["Trusted brand", "Security-focused"],
        prosZh: ["品牌可信", "注重安全"],
        cons: ["Requires software", "Not browser-based", "Tracks usage"],
        consZh: ["需安装软件", "非浏览器端", "追踪使用"],
      },
    ],
    toolboxProAdvantages: [
      "Uses Web Crypto API (cryptographically secure)",
      "No account, no storage, no tracking",
      "Fully customizable length and character sets",
      "Instant generation — no loading",
    ],
    toolboxProAdvantagesZh: [
      "使用 Web Crypto API，密码学安全",
      "无账户、无存储、无追踪",
      "长度和字符集完全可定制",
      "即时生成，无需等待",
    ],
  },
  "word-counter": {
    toolName: "Word & Character Counter",
    toolNameZh: "字数统计",
    competitors: [
      {
        name: "WordCounter.net",
        url: "https://wordcounter.net",
        pros: ["Detailed statistics", "Keyword density"],
        prosZh: ["详细统计", "关键词密度"],
        cons: ["Heavy ads", "Slow loading", "Tracks usage"],
        consZh: ["广告多", "加载缓慢", "追踪使用"],
      },
      {
        name: "Online-Word-Counter",
        url: "https://online-word-counter.com",
        pros: ["Simple interface"],
        prosZh: ["界面简洁"],
        cons: ["Limited features", "Ads everywhere", "No reading time estimate"],
        consZh: ["功能有限", "广告泛滥", "无阅读时间估算"],
      },
    ],
    toolboxProAdvantages: [
      "Clean, ad-free interface",
      "Real-time counting as you type",
      "Reading time and speaking time estimates",
      "Top keyword frequency analysis",
    ],
    toolboxProAdvantagesZh: [
      "界面清爽无广告",
      "实时统计字数",
      "阅读时间和演讲时间估算",
      "高频关键词分析",
    ],
  },
  "color-converter": {
    toolName: "Color Converter",
    toolNameZh: "颜色转换器",
    competitors: [
      {
        name: "Color Converter (color-converter.com)",
        url: "https://color-converter.com",
        pros: ["Multiple formats"],
        prosZh: ["多格式支持"],
        cons: ["Ads", "No visual picker", "Mobile-unfriendly"],
        consZh: ["有广告", "无可视选择器", "移动端不友好"],
      },
      {
        name: "W3Schools Color Picker",
        url: "https://w3schools.com/colors/colors_picker.asp",
        pros: ["Educational", "Part of W3Schools"],
        prosZh: ["教学资源", "W3Schools 生态"],
        cons: ["Limited formats", "No copy-to-clipboard", "Not a standalone tool"],
        consZh: ["格式有限", "无复制功能", "非独立工具"],
      },
    ],
    toolboxProAdvantages: [
      "Visual color picker with instant preview",
      "HEX, RGB, HSL, CMYK, HSV all at once",
      "One-click copy for any format",
      "Works perfectly on mobile",
    ],
    toolboxProAdvantagesZh: [
      "可视化取色器即时预览",
      "HEX、RGB、HSL、CMYK、HSV 一站式",
      "任意格式一键复制",
      "移动端完美适配",
    ],
  },
  "regex-tester": {
    toolName: "Regex Tester",
    toolNameZh: "正则表达式测试",
    competitors: [
      {
        name: "Regex101",
        url: "https://regex101.com",
        pros: ["Full regex engine", "Community patterns"],
        prosZh: ["完整正则引擎", "社区模式库"],
        cons: ["Complex for beginners", "Requires language selection", "Dated interface"],
        consZh: ["新手难上手", "需选择语言", "界面老旧"],
      },
      {
        name: "RegExr",
        url: "https://regexr.com",
        pros: ["Visual explanation", "Cheatsheet"],
        prosZh: ["可视化解释", "速查表"],
        cons: ["Can be slow with large inputs", "Learning curve"],
        consZh: ["大输入时较慢", "有学习成本"],
      },
    ],
    toolboxProAdvantages: [
      "Simple, beginner-friendly interface",
      "Instant real-time matching",
      "No configuration needed",
      "Mobile-optimized design",
    ],
    toolboxProAdvantagesZh: [
      "新手友好的简洁界面",
      "即时实时匹配",
      "无需配置",
      "移动端优化设计",
    ],
  },
  "pdf-splitter": {
    toolName: "PDF Splitter",
    toolNameZh: "PDF 拆分器",
    competitors: [
      {
        name: "iLovePDF Split",
        url: "https://ilovepdf.com/split_pdf",
        pros: ["Multiple split modes", "Clean interface"],
        prosZh: ["多种拆分模式", "界面清爽"],
        cons: ["File size limits", "Server processing", "Daily limits on free tier"],
        consZh: ["文件大小限制", "服务器处理", "免费版有日限制"],
      },
    ],
    toolboxProAdvantages: [
      "Unlimited splits — no daily limits",
      "Files never leave your browser",
      "Extract specific pages or ranges",
      "No account required",
    ],
    toolboxProAdvantagesZh: [
      "无限拆分，无日限制",
      "文件从不离开浏览器",
      "提取特定页面或范围",
      "无需注册账户",
    ],
  },
  "image-resizer": {
    toolName: "Image Resizer",
    toolNameZh: "图片缩放",
    competitors: [
      {
        name: "Birme",
        url: "https://birme.net",
        pros: ["Batch resize", "Auto-crop"],
        prosZh: ["批量缩放", "自动裁剪"],
        cons: ["Requires upload", "No privacy guarantee", "Limited free tier"],
        consZh: ["需上传文件", "无隐私保障", "免费版受限"],
      },
    ],
    toolboxProAdvantages: [
      "Resize without uploading — all client-side",
      "Aspect ratio lock to prevent distortion",
      "Preview before downloading",
      "No file size or batch limits",
    ],
    toolboxProAdvantagesZh: [
      "无需上传，纯客户端缩放",
      "锁定宽高比防变形",
      "下载前预览",
      "无文件大小或批量限制",
    ],
  },
  "hash-generator": {
    toolName: "Hash Generator",
    toolNameZh: "哈希生成器",
    competitors: [
      {
        name: "Online Hash Calculator",
        url: "https://emn178.github.io/online-tools",
        pros: ["Multiple algorithms"],
        prosZh: ["多算法支持"],
        cons: ["Dated interface", "No file hashing", "Ads"],
        consZh: ["界面老旧", "无文件哈希", "有广告"],
      },
    ],
    toolboxProAdvantages: [
      "SHA-256, SHA-384, SHA-512 support",
      "Hash text or files — both supported",
      "Client-side processing for privacy",
      "Instant results with one-click copy",
    ],
    toolboxProAdvantagesZh: [
      "支持 SHA-256、SHA-384、SHA-512",
      "文本和文件哈希均支持",
      "客户端处理保护隐私",
      "即时结果一键复制",
    ],
  },
  "uuid-generator": {
    toolName: "UUID Generator",
    toolNameZh: "UUID 生成器",
    competitors: [
      {
        name: "UUIDGenerator.net",
        url: "https://uuidgenerator.net",
        pros: ["Simple interface", "Batch generation"],
        prosZh: ["界面简洁", "批量生成"],
        cons: ["Server-side generation", "Ads", "Limited format options"],
        consZh: ["服务器端生成", "有广告", "格式选项有限"],
      },
    ],
    toolboxProAdvantages: [
      "Generates v4 UUIDs using Web Crypto API",
      "Bulk generation up to 1000 UUIDs",
      "Copy individual or all UUIDs",
      "No data sent to servers",
    ],
    toolboxProAdvantagesZh: [
      "用 Web Crypto API 生成 v4 UUID",
      "批量生成最多 1000 个 UUID",
      "可复制单个或全部 UUID",
      "数据不发送服务器",
    ],
  },
  "case-converter": {
    toolName: "Text Case Converter",
    toolNameZh: "文字大小写转换",
    competitors: [
      {
        name: "ConvertCase.net",
        url: "https://convertcase.net",
        pros: ["Multiple case types"],
        prosZh: ["多种大小写"],
        cons: ["Heavy ads", "Slow loading", "Server processing"],
        consZh: ["广告多", "加载缓慢", "服务器处理"],
      },
    ],
    toolboxProAdvantages: [
      "Instant conversion — no waiting",
      "UPPER, lower, Title, camelCase, snake_case, and more",
      "No ads, no tracking",
      "Works offline after first load",
    ],
    toolboxProAdvantagesZh: [
      "即时转换，无需等待",
      "大写、小写、标题、驼峰、蛇形等多种格式",
      "无广告、无追踪",
      "首次加载后可离线使用",
    ],
  },
  "text-diff-checker": {
    toolName: "Text Diff Checker",
    toolNameZh: "文本差异对比",
    competitors: [
      {
        name: "DiffChecker.com",
        url: "https://diffchecker.com",
        pros: ["File upload support", "PDF diff"],
        prosZh: ["支持文件上传", "PDF 对比"],
        cons: ["Requires account for history", "Server processing", "Limited free features"],
        consZh: ["历史记录需注册", "服务器处理", "免费功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "No account needed — use immediately",
      "Files never leave your browser",
      "Line-by-line and character-by-character diff",
      "Copy diff results with one click",
    ],
    toolboxProAdvantagesZh: [
      "无需账户，即开即用",
      "文件从不离开浏览器",
      "逐行和逐字符差异对比",
      "一键复制差异结果",
    ],
  },
  "css-gradient": {
    toolName: "CSS Gradient Generator",
    toolNameZh: "CSS 渐变生成器",
    competitors: [
      {
        name: "CSSGradient.io",
        url: "https://cssgradient.io",
        pros: ["Visual editor", "Gradient library"],
        prosZh: ["可视化编辑", "渐变库"],
        cons: ["Complex interface for beginners", "Some features require signup"],
        consZh: ["新手难上手", "部分功能需注册"],
      },
    ],
    toolboxProAdvantages: [
      "Simple, intuitive gradient builder",
      "Linear and radial gradients",
      "Copy CSS with one click",
      "Real-time preview",
    ],
    toolboxProAdvantagesZh: [
      "简洁直观的渐变构建器",
      "线性和径向渐变",
      "一键复制 CSS",
      "实时预览",
    ],
  },
  "csv-viewer": {
    toolName: "CSV Viewer & Formatter",
    toolNameZh: "CSV 查看器",
    competitors: [
      {
        name: "CSVViewer.net",
        url: "https://csvviewer.net",
        pros: ["Basic viewing"],
        prosZh: ["基本查看"],
        cons: ["No editing", "Ads", "Limited format support"],
        consZh: ["不可编辑", "有广告", "格式支持有限"],
      },
    ],
    toolboxProAdvantages: [
      "Auto-detect delimiters and encoding",
      "Sort, filter, and search CSV data",
      "Export to different formats",
      "Handles large files efficiently",
    ],
    toolboxProAdvantagesZh: [
      "自动检测分隔符和编码",
      "排序、筛选和搜索 CSV",
      "导出为不同格式",
      "高效处理大文件",
    ],
  },
  "lorem-ipsum-generator": {
    toolName: "Lorem Ipsum Generator",
    toolNameZh: "Lorem Ipsum 生成器",
    competitors: [
      {
        name: "Lipsum.com",
        url: "https://lipsum.com",
        pros: ["Classic generator", "Multiple languages"],
        prosZh: ["经典生成器", "多语言支持"],
        cons: ["Dated design", "Limited customization", "No paragraph control"],
        consZh: ["设计过时", "定制性有限", "无段落控制"],
      },
    ],
    toolboxProAdvantages: [
      "Custom paragraph count and word count",
      "Start with or without Lorem ipsum",
      "Include HTML tags option",
      "Copy with one click",
    ],
    toolboxProAdvantagesZh: [
      "自定义段落数和字数",
      "可选是否以 Lorem ipsum 开头",
      "可选包含 HTML 标签",
      "一键复制",
    ],
  },
  "markdown-to-html": {
    toolName: "Markdown to HTML Converter",
    toolNameZh: "Markdown 转 HTML",
    competitors: [
      {
        name: "MarkdownHere",
        url: "https://markdown-here.com",
        pros: ["Browser extension", "Email friendly"],
        prosZh: ["浏览器插件", "邮件友好"],
        cons: ["Requires extension install", "Limited formatting options"],
        consZh: ["需安装插件", "格式选项有限"],
      },
    ],
    toolboxProAdvantages: [
      "No installation required — browser-based",
      "Real-time preview as you type",
      "Supports GitHub Flavored Markdown",
      "Copy HTML or download as file",
    ],
    toolboxProAdvantagesZh: [
      "无需安装，浏览器端运行",
      "实时预览输入内容",
      "支持 GitHub 风格 Markdown",
      "复制 HTML 或下载文件",
    ],
  },
  "html-entity-converter": {
    toolName: "HTML Entity Converter",
    toolNameZh: "HTML 实体转换",
    competitors: [
      {
        name: "FreeFormatter.com",
        url: "https://freeformatter.com/html-entity-encoder.html",
        pros: ["Multiple encoding types"],
        prosZh: ["多种编码类型"],
        cons: ["Heavy page", "Many ads", "Slow loading"],
        consZh: ["页面臃肿", "广告多", "加载缓慢"],
      },
    ],
    toolboxProAdvantages: [
      "Instant encode/decode toggle",
      "Handles all HTML entities",
      "Clean, fast interface",
      "One-click copy",
    ],
    toolboxProAdvantagesZh: [
      "即时编解码切换",
      "处理所有 HTML 实体",
      "清爽快速的界面",
      "一键复制",
    ],
  },
  "timestamp-converter": {
    toolName: "Timestamp Converter",
    toolNameZh: "时间戳转换器",
    competitors: [
      {
        name: "EpochConverter.com",
        url: "https://epochconverter.com",
        pros: ["Calendar view", "Multiple formats"],
        prosZh: ["日历视图", "多格式支持"],
        cons: ["Ads", "Dated design", "Limited timezone support"],
        consZh: ["有广告", "设计过时", "时区支持有限"],
      },
    ],
    toolboxProAdvantages: [
      "Convert timestamp to date and back",
      "Supports multiple date formats",
      "Timezone-aware conversions",
      "No ads, instant results",
    ],
    toolboxProAdvantagesZh: [
      "时间戳与日期互转",
      "支持多种日期格式",
      "时区感知转换",
      "无广告，即时结果",
    ],
  },
  "jwt-decoder": {
    toolName: "JWT Decoder",
    toolNameZh: "JWT 解码器",
    competitors: [
      {
        name: "jwt.io",
        url: "https://jwt.io",
        pros: ["Industry standard", "Debug features"],
        prosZh: ["行业标准", "调试功能"],
        cons: ["Server-side (sends token)", "Complex interface", "Security concern with sensitive tokens"],
        consZh: ["服务器端处理(发Token)", "界面复杂", "敏感Token有安全风险"],
      },
    ],
    toolboxProAdvantages: [
      "100% client-side — token never leaves browser",
      "Clear header/payload/signature display",
      "No security risk for sensitive tokens",
      "Supports all JWT algorithms",
    ],
    toolboxProAdvantagesZh: [
      "100%客户端，Token不离浏览器",
      "清晰展示头部/载荷/签名",
      "敏感 Token 无安全风险",
      "支持所有 JWT 算法",
    ],
  },
  "ip-calculator": {
    toolName: "IP Subnet Calculator",
    toolNameZh: "IP 子网计算器",
    competitors: [
      {
        name: "ipaddressguide.com",
        url: "https://ipaddressguide.com",
        pros: ["Simple interface"],
        prosZh: ["界面简洁"],
        cons: ["IPv4 only", "Ads", "No bulk calculation"],
        consZh: ["仅支持 IPv4", "有广告", "无批量计算"],
      },
    ],
    toolboxProAdvantages: [
      "Supports both IPv4 and IPv6",
      "Calculate subnet, broadcast, host range",
      "CIDR notation support",
      "Clean, ad-free interface",
    ],
    toolboxProAdvantagesZh: [
      "同时支持 IPv4 和 IPv6",
      "计算子网、广播、主机范围",
      "支持 CIDR 表示法",
      "界面清爽无广告",
    ],
  },
  "color-picker": {
    toolName: "Color Picker from Image",
    toolNameZh: "图片取色器",
    competitors: [
      {
        name: "ColorPicker.com",
        url: "https://colorpicker.com",
        pros: ["Wheel interface"],
        prosZh: ["色轮界面"],
        cons: ["No image upload", "Limited export formats"],
        consZh: ["不可上传图片", "导出格式有限"],
      },
    ],
    toolboxProAdvantages: [
      "Pick colors from uploaded images",
      "Get HEX, RGB, HSL values instantly",
      "Zoom into pixels for precise picking",
      "No upload to servers — all local",
    ],
    toolboxProAdvantagesZh: [
      "从上传图片中取色",
      "即时获取 HEX、RGB、HSL",
      "像素级放大精准取色",
      "不上传服务器，全程本地",
    ],
  },
  "dice-roller": {
    toolName: "Dice Roller",
    toolNameZh: "骰子模拟器",
    competitors: [
      {
        name: "DiceRoller.com",
        url: "https://diceroller.com",
        pros: ["Multiple dice types"],
        prosZh: ["多种骰子"],
        cons: ["Ads", "No animation", "Limited statistics"],
        consZh: ["有广告", "无动画效果", "统计有限"],
      },
    ],
    toolboxProAdvantages: [
      "Roll D4, D6, D8, D10, D12, D20",
      "Roll multiple dice at once",
      "Track roll history and statistics",
      "Smooth roll animation",
    ],
    toolboxProAdvantagesZh: [
      "支持 D4、D6、D8、D10、D12、D20",
      "一次掷多个骰子",
      "记录投掷历史和统计",
      "流畅投掷动画",
    ],
  },
  "password-strength": {
    toolName: "Password Strength Checker",
    toolNameZh: "密码强度检测",
    competitors: [
      {
        name: "HowSecureIsMyPassword.net",
        url: "https://howsecureismypassword.net",
        pros: ["Crack time estimate"],
        prosZh: ["破解时间估算"],
        cons: ["Sends password to server", "Privacy risk", "Limited analysis"],
        consZh: ["密码发送服务器", "隐私风险", "分析有限"],
      },
    ],
    toolboxProAdvantages: [
      "Password never leaves your browser",
      "Real-time strength analysis",
      "Shows crack time estimate",
      "Suggestions for improvement",
    ],
    toolboxProAdvantagesZh: [
      "密码从不离开浏览器",
      "实时强度分析",
      "显示破解时间估算",
      "改进建议",
    ],
  },
  "percentage-calculator": {
    toolName: "Percentage Calculator",
    toolNameZh: "百分比计算器",
    competitors: [
      {
        name: "Calculator.net",
        url: "https://calculator.net/percent-calculator.html",
        pros: ["Multiple calculators"],
        prosZh: ["多种计算器"],
        cons: ["Many ads", "Slow page", "Confusing interface"],
        consZh: ["广告多", "页面缓慢", "界面混乱"],
      },
    ],
    toolboxProAdvantages: [
      "Calculate percentages, increases, decreases",
      "What-if scenarios",
      "Instant results — no page reload",
      "Clean, focused interface",
    ],
    toolboxProAdvantagesZh: [
      "计算百分比、增减幅度",
      "假设场景分析",
      "即时结果，无页面刷新",
      "清爽专注的界面",
    ],
  },
  "bmi-calculator": {
    toolName: "BMI Calculator",
    toolNameZh: "BMI 计算器",
    competitors: [
      {
        name: "CDC BMI Calculator",
        url: "https://cdc.gov/bmi",
        pros: ["Government source", "Reliable"],
        prosZh: ["政府来源", "可靠"],
        cons: ["Basic interface", "US-centric", "No history tracking"],
        consZh: ["界面简陋", "偏美式", "无历史记录"],
      },
    ],
    toolboxProAdvantages: [
      "Metric and Imperial units",
      "Health category with recommendations",
      "Clean, modern interface",
      "Mobile-friendly design",
    ],
    toolboxProAdvantagesZh: [
      "公制和英制单位",
      "健康分类和建议",
      "清爽现代界面",
      "移动端友好设计",
    ],
  },
  "dns-lookup": {
    toolName: "DNS Lookup",
    toolNameZh: "DNS 查询",
    competitors: [
      {
        name: "MXToolbox",
        url: "https://mxtoolbox.com",
        pros: ["Comprehensive tools", "Email diagnostics"],
        prosZh: ["工具全面", "邮件诊断"],
        cons: ["Rate limits", "Requires signup for full features", "Server-side"],
        consZh: ["有频率限制", "完整功能需注册", "服务器端"],
      },
    ],
    toolboxProAdvantages: [
      "Query A, AAAA, MX, NS, TXT, CAA, SOA records",
      "No rate limits",
      "No account required",
      "Instant results",
    ],
    toolboxProAdvantagesZh: [
      "查询 A、AAAA、MX、NS、TXT、CAA、SOA 记录",
      "无频率限制",
      "无需注册账户",
      "即时结果",
    ],
  },
  "age-calculator": {
    toolName: "Age Calculator",
    toolNameZh: "年龄计算器",
    competitors: [
      {
        name: "Calculator.net",
        url: "#",
        pros: ["Wide range"],
        prosZh: ["功能广泛"],
        cons: ["Ad-heavy", "Outdated design", "No dark mode"],
        consZh: ["广告多", "设计过时", "无暗黑模式"],
      },
      {
        name: "GoodCalculators",
        url: "#",
        pros: ["Many calculators"],
        prosZh: ["计算器多"],
        cons: ["Slow loading", "Ads", "Limited customization"],
        consZh: ["加载缓慢", "有广告", "定制性有限"],
      },
    ],
    toolboxProAdvantages: [
      "Dark mode support",
      "Instant results with no server round-trip",
      "Works offline once loaded",
    ],
    toolboxProAdvantagesZh: [
      "支持暗黑模式",
      "即时结果，无服务器往返",
      "加载后可离线使用",
    ],
  },
  "area-converter": {
    toolName: "Area Converter",
    toolNameZh: "面积转换器",
    competitors: [
      {
        name: "RapidTables",
        url: "#",
        pros: ["Many unit types"],
        prosZh: ["单位类型多"],
        cons: ["Ad-heavy", "Outdated UI", "No customization"],
        consZh: ["广告多", "界面过时", "不可定制"],
      },
      {
        name: "UnitConverters.net",
        url: "#",
        pros: ["Extensive units"],
        prosZh: ["单位丰富"],
        cons: ["Cluttered interface", "No dark mode", "Sluggish"],
        consZh: ["界面杂乱", "无暗黑模式", "响应迟缓"],
      },
    ],
    toolboxProAdvantages: [
      "Dark mode support",
      "Instant results with no server round-trip",
      "Works offline once loaded",
    ],
    toolboxProAdvantagesZh: [
      "支持暗黑模式",
      "即时结果，无服务器往返",
      "加载后可离线使用",
    ],
  },
  "aspect-ratio-calculator": {
    toolName: "Aspect Ratio Calculator",
    toolNameZh: "宽高比计算",
    competitors: [
      {
        name: "Calculator.net",
        url: "#",
        pros: ["Wide range"],
        prosZh: ["功能广泛"],
        cons: ["Ad-heavy", "Outdated design", "No dark mode"],
        consZh: ["广告多", "设计过时", "无暗黑模式"],
      },
      {
        name: "GoodCalculators",
        url: "#",
        pros: ["Many calculators"],
        prosZh: ["计算器多"],
        cons: ["Slow loading", "Ads", "Limited customization"],
        consZh: ["加载缓慢", "有广告", "定制性有限"],
      },
    ],
    toolboxProAdvantages: [
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
    ],
    toolboxProAdvantagesZh: [
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
    ],
  },
  "audio-converter": {
    toolName: "Audio Converter",
    toolNameZh: "音频转换",
    competitors: [
      {
        name: "Audacity",
        url: "#",
        pros: ["Full-featured", "Open source"],
        prosZh: ["功能全面", "开源"],
        cons: ["Desktop install required", "Steep learning curve", "Overkill for simple tasks"],
        consZh: ["需桌面安装", "学习曲线陡", "简单任务太重"],
      },
      {
        name: "OnlineAudioConverter",
        url: "#",
        pros: ["Quick"],
        prosZh: ["快速"],
        cons: ["Uploads files", "Format limitations", "Ad-heavy"],
        consZh: ["需上传文件", "格式有限制", "广告多"],
      },
    ],
    toolboxProAdvantages: [
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
    ],
    toolboxProAdvantagesZh: [
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
    ],
  },
  "audio-cutter": {
    toolName: "Audio Cutter",
    toolNameZh: "音频裁剪",
    competitors: [
      {
        name: "Audacity",
        url: "#",
        pros: ["Full-featured", "Open source"],
        prosZh: ["功能全面", "开源"],
        cons: ["Desktop install required", "Steep learning curve", "Overkill for simple tasks"],
        consZh: ["需桌面安装", "学习曲线陡", "简单任务太重"],
      },
      {
        name: "OnlineAudioConverter",
        url: "#",
        pros: ["Quick"],
        prosZh: ["快速"],
        cons: ["Uploads files", "Format limitations", "Ad-heavy"],
        consZh: ["需上传文件", "格式有限制", "广告多"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "audio-merger": {
    toolName: "Audio Merger",
    toolNameZh: "音频合并",
    competitors: [
      {
        name: "Audacity",
        url: "#",
        pros: ["Full-featured", "Open source"],
        prosZh: ["功能全面", "开源"],
        cons: ["Desktop install required", "Steep learning curve", "Overkill for simple tasks"],
        consZh: ["需桌面安装", "学习曲线陡", "简单任务太重"],
      },
      {
        name: "OnlineAudioConverter",
        url: "#",
        pros: ["Quick"],
        prosZh: ["快速"],
        cons: ["Uploads files", "Format limitations", "Ad-heavy"],
        consZh: ["需上传文件", "格式有限制", "广告多"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "barcode-generator": {
    toolName: "Barcode & QR Code Generator",
    toolNameZh: "条码与二维码生成器",
    competitors: [
      {
        name: "RapidTables",
        url: "#",
        pros: ["Many unit types"],
        prosZh: ["单位类型多"],
        cons: ["Ad-heavy", "Outdated UI", "No customization"],
        consZh: ["广告多", "界面过时", "不可定制"],
      },
      {
        name: "UnitConverters.net",
        url: "#",
        pros: ["Extensive units"],
        prosZh: ["单位丰富"],
        cons: ["Cluttered interface", "No dark mode", "Sluggish"],
        consZh: ["界面杂乱", "无暗黑模式", "响应迟缓"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "base64-encode-decode": {
    toolName: "Base64 Encoder/Decoder",
    toolNameZh: "Base64 编码/解码",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "Dark mode support",
      "Instant results with no server round-trip",
      "Works offline once loaded",
    ],
    toolboxProAdvantagesZh: [
      "支持暗黑模式",
      "即时结果，无服务器往返",
      "加载后可离线使用",
    ],
  },
  "binary-to-text": {
    toolName: "Binary to Text",
    toolNameZh: "二进制转文本",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "caesar-cipher": {
    toolName: "Caesar Cipher",
    toolNameZh: "凯撒密码",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
    ],
    toolboxProAdvantagesZh: [
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
    ],
  },
  "color-blindness-simulator": {
    toolName: "Color Blindness Simulator",
    toolNameZh: "色盲模拟器",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "color-palette": {
    toolName: "Color Palette Generator",
    toolNameZh: "配色方案生成",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
      "Dark mode support",
    ],
    toolboxProAdvantagesZh: [
      "无需注册或登录",
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
    ],
  },
  "countdown-timer": {
    toolName: "Countdown Timer",
    toolNameZh: "倒计时器",
    competitors: [
      {
        name: "Calculator.net",
        url: "#",
        pros: ["Wide range"],
        prosZh: ["功能广泛"],
        cons: ["Ad-heavy", "Outdated design", "No dark mode"],
        consZh: ["广告多", "设计过时", "无暗黑模式"],
      },
      {
        name: "GoodCalculators",
        url: "#",
        pros: ["Many calculators"],
        prosZh: ["计算器多"],
        cons: ["Slow loading", "Ads", "Limited customization"],
        consZh: ["加载缓慢", "有广告", "定制性有限"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "cron-parser": {
    toolName: "Cron Expression Parser",
    toolNameZh: "Cron 表达式解析",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "css-minifier": {
    toolName: "CSS Minifier",
    toolNameZh: "CSS 压缩器",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "css-shadow": {
    toolName: "CSS Box Shadow Generator",
    toolNameZh: "CSS 阴影生成器",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "data-size-converter": {
    toolName: "Data Size Converter",
    toolNameZh: "数据大小转换",
    competitors: [
      {
        name: "RapidTables",
        url: "#",
        pros: ["Many unit types"],
        prosZh: ["单位类型多"],
        cons: ["Ad-heavy", "Outdated UI", "No customization"],
        consZh: ["广告多", "界面过时", "不可定制"],
      },
      {
        name: "UnitConverters.net",
        url: "#",
        pros: ["Extensive units"],
        prosZh: ["单位丰富"],
        cons: ["Cluttered interface", "No dark mode", "Sluggish"],
        consZh: ["界面杂乱", "无暗黑模式", "响应迟缓"],
      },
    ],
    toolboxProAdvantages: [
      "Dark mode support",
      "Instant results with no server round-trip",
      "Works offline once loaded",
    ],
    toolboxProAdvantagesZh: [
      "支持暗黑模式",
      "即时结果，无服务器往返",
      "加载后可离线使用",
    ],
  },
  "days-between": {
    toolName: "Days Between Dates",
    toolNameZh: "日期计算器",
    competitors: [
      {
        name: "Calculator.net",
        url: "#",
        pros: ["Wide range"],
        prosZh: ["功能广泛"],
        cons: ["Ad-heavy", "Outdated design", "No dark mode"],
        consZh: ["广告多", "设计过时", "无暗黑模式"],
      },
      {
        name: "GoodCalculators",
        url: "#",
        pros: ["Many calculators"],
        prosZh: ["计算器多"],
        cons: ["Slow loading", "Ads", "Limited customization"],
        consZh: ["加载缓慢", "有广告", "定制性有限"],
      },
    ],
    toolboxProAdvantages: [
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
      "Dark mode support",
    ],
    toolboxProAdvantagesZh: [
      "无需注册或登录",
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
    ],
  },
  "decision-maker": {
    toolName: "Decision Maker",
    toolNameZh: "决策助手",
    competitors: [
      {
        name: "Calculator.net",
        url: "#",
        pros: ["Wide range"],
        prosZh: ["功能广泛"],
        cons: ["Ad-heavy", "Outdated design", "No dark mode"],
        consZh: ["广告多", "设计过时", "无暗黑模式"],
      },
      {
        name: "GoodCalculators",
        url: "#",
        pros: ["Many calculators"],
        prosZh: ["计算器多"],
        cons: ["Slow loading", "Ads", "Limited customization"],
        consZh: ["加载缓慢", "有广告", "定制性有限"],
      },
    ],
    toolboxProAdvantages: [
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
      "Dark mode support",
    ],
    toolboxProAdvantagesZh: [
      "无需注册或登录",
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
    ],
  },
  "emoji-remover": {
    toolName: "Emoji Remover",
    toolNameZh: "表情符号移除",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
    ],
    toolboxProAdvantagesZh: [
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
      "除浏览器内存外无大小限制",
    ],
  },
  "gif-maker": {
    toolName: "GIF Maker",
    toolNameZh: "GIF 制作器",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "html-preview": {
    toolName: "HTML Preview",
    toolNameZh: "HTML 预览",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "html-tag-stripper": {
    toolName: "HTML Tag Stripper",
    toolNameZh: "HTML 标签移除",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
    ],
    toolboxProAdvantagesZh: [
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
      "除浏览器内存外无大小限制",
    ],
  },
  "html-to-jsx": {
    toolName: "HTML to JSX Converter",
    toolNameZh: "HTML 转 JSX",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
    ],
    toolboxProAdvantagesZh: [
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
    ],
  },
  "http-status-codes": {
    toolName: "HTTP Status Codes",
    toolNameZh: "HTTP 状态码查询",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "image-border": {
    toolName: "Image Border",
    toolNameZh: "图片边框",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
      "Dark mode support",
    ],
    toolboxProAdvantagesZh: [
      "无需注册或登录",
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
    ],
  },
  "image-collage": {
    toolName: "Photo Collage Maker",
    toolNameZh: "拼图制作器",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "image-converter": {
    toolName: "Image Format Converter",
    toolNameZh: "图片格式转换",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "image-cropper": {
    toolName: "Image Cropper",
    toolNameZh: "图片裁剪",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "image-filters": {
    toolName: "Image Filters",
    toolNameZh: "图片滤镜",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "Dark mode support",
      "Instant results with no server round-trip",
      "Works offline once loaded",
    ],
    toolboxProAdvantagesZh: [
      "支持暗黑模式",
      "即时结果，无服务器往返",
      "加载后可离线使用",
    ],
  },
  "image-flip": {
    toolName: "Image Flip & Rotate",
    toolNameZh: "图片翻转与旋转",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "image-invert": {
    toolName: "Image Invert",
    toolNameZh: "图片反色",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "image-merge": {
    toolName: "Image Merger",
    toolNameZh: "图片合并",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "Dark mode support",
      "Instant results with no server round-trip",
      "Works offline once loaded",
    ],
    toolboxProAdvantagesZh: [
      "支持暗黑模式",
      "即时结果，无服务器往返",
      "加载后可离线使用",
    ],
  },
  "image-splitter": {
    toolName: "Image Splitter",
    toolNameZh: "图片分割",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "image-to-base64": {
    toolName: "Image to Base64",
    toolNameZh: "图片转 Base64",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "image-to-pdf": {
    toolName: "Image to PDF",
    toolNameZh: "图片转 PDF",
    competitors: [
      {
        name: "iLovePDF",
        url: "#",
        pros: ["Popular", "Many features"],
        prosZh: ["受欢迎", "功能丰富"],
        cons: ["Uploads files to server", "File size limits", "Premium paywall"],
        consZh: ["文件上传服务器", "文件大小限制", "高级付费墙"],
      },
      {
        name: "Smallpdf",
        url: "#",
        pros: ["Clean UI"],
        prosZh: ["界面清爽"],
        cons: ["2 tasks per day free", "Uploads to cloud", "Privacy concerns"],
        consZh: ["每天仅 2 次免费", "上传至云端", "隐私隐患"],
      },
    ],
    toolboxProAdvantages: [
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
    ],
    toolboxProAdvantagesZh: [
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
    ],
  },
  "image-to-sketch": {
    toolName: "Image to Sketch",
    toolNameZh: "图片转素描",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
    ],
    toolboxProAdvantagesZh: [
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
      "除浏览器内存外无大小限制",
    ],
  },
  "image-watermark": {
    toolName: "Image Watermark",
    toolNameZh: "图片水印",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "json-diff": {
    toolName: "JSON Diff",
    toolNameZh: "JSON 差异对比",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "json-to-typescript": {
    toolName: "JSON to TypeScript",
    toolNameZh: "JSON 转 TypeScript",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "json-to-yaml": {
    toolName: "JSON to YAML Converter",
    toolNameZh: "JSON 转 YAML",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
      "Dark mode support",
    ],
    toolboxProAdvantagesZh: [
      "无需注册或登录",
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
    ],
  },
  "jwt-generator": {
    toolName: "JWT Generator",
    toolNameZh: "JWT 生成器",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "length-converter": {
    toolName: "Length Converter",
    toolNameZh: "长度转换器",
    competitors: [
      {
        name: "RapidTables",
        url: "#",
        pros: ["Many unit types"],
        prosZh: ["单位类型多"],
        cons: ["Ad-heavy", "Outdated UI", "No customization"],
        consZh: ["广告多", "界面过时", "不可定制"],
      },
      {
        name: "UnitConverters.net",
        url: "#",
        pros: ["Extensive units"],
        prosZh: ["单位丰富"],
        cons: ["Cluttered interface", "No dark mode", "Sluggish"],
        consZh: ["界面杂乱", "无暗黑模式", "响应迟缓"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "meme-generator": {
    toolName: "Meme Generator",
    toolNameZh: "表情包制作",
    competitors: [
      {
        name: "ILoveIMG",
        url: "#",
        pros: ["Popular", "Fast"],
        prosZh: ["受欢迎", "速度快"],
        cons: ["Uploads to server", "File size limits", "Watermark on free tier"],
        consZh: ["上传至服务器", "文件大小限制", "免费版有水印"],
      },
      {
        name: "TinyPNG",
        url: "#",
        pros: ["Good compression"],
        prosZh: ["压缩效果好"],
        cons: ["Uploads required", "20 image limit", "No editing features"],
        consZh: ["需上传", "限 20 张图", "无编辑功能"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "morse-code-converter": {
    toolName: "Morse Code Converter",
    toolNameZh: "摩斯密码转换",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "number-base-converter": {
    toolName: "Number Base Converter",
    toolNameZh: "进制转换器",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
    ],
    toolboxProAdvantagesZh: [
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
    ],
  },
  "online-notepad": {
    toolName: "Online Notepad",
    toolNameZh: "在线记事本",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "palindrome-checker": {
    toolName: "Palindrome Checker",
    toolNameZh: "回文检查器",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "Dark mode support",
      "Instant results with no server round-trip",
      "Works offline once loaded",
    ],
    toolboxProAdvantagesZh: [
      "支持暗黑模式",
      "即时结果，无服务器往返",
      "加载后可离线使用",
    ],
  },
  "pdf-page-remover": {
    toolName: "PDF Page Remover",
    toolNameZh: "PDF 页面删除",
    competitors: [
      {
        name: "iLovePDF",
        url: "#",
        pros: ["Popular", "Many features"],
        prosZh: ["受欢迎", "功能丰富"],
        cons: ["Uploads files to server", "File size limits", "Premium paywall"],
        consZh: ["文件上传服务器", "文件大小限制", "高级付费墙"],
      },
      {
        name: "Smallpdf",
        url: "#",
        pros: ["Clean UI"],
        prosZh: ["界面清爽"],
        cons: ["2 tasks per day free", "Uploads to cloud", "Privacy concerns"],
        consZh: ["每天仅 2 次免费", "上传至云端", "隐私隐患"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "pdf-rotator": {
    toolName: "PDF Rotator",
    toolNameZh: "PDF 旋转",
    competitors: [
      {
        name: "iLovePDF",
        url: "#",
        pros: ["Popular", "Many features"],
        prosZh: ["受欢迎", "功能丰富"],
        cons: ["Uploads files to server", "File size limits", "Premium paywall"],
        consZh: ["文件上传服务器", "文件大小限制", "高级付费墙"],
      },
      {
        name: "Smallpdf",
        url: "#",
        pros: ["Clean UI"],
        prosZh: ["界面清爽"],
        cons: ["2 tasks per day free", "Uploads to cloud", "Privacy concerns"],
        consZh: ["每天仅 2 次免费", "上传至云端", "隐私隐患"],
      },
    ],
    toolboxProAdvantages: [
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
    ],
    toolboxProAdvantagesZh: [
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
    ],
  },
  "qr-reader": {
    toolName: "QR Code Reader",
    toolNameZh: "二维码读取",
    competitors: [
      {
        name: "RapidTables",
        url: "#",
        pros: ["Many unit types"],
        prosZh: ["单位类型多"],
        cons: ["Ad-heavy", "Outdated UI", "No customization"],
        consZh: ["广告多", "界面过时", "不可定制"],
      },
      {
        name: "UnitConverters.net",
        url: "#",
        pros: ["Extensive units"],
        prosZh: ["单位丰富"],
        cons: ["Cluttered interface", "No dark mode", "Sluggish"],
        consZh: ["界面杂乱", "无暗黑模式", "响应迟缓"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "random-number-generator": {
    toolName: "Random Number Generator",
    toolNameZh: "随机数生成器",
    competitors: [
      {
        name: "Calculator.net",
        url: "#",
        pros: ["Wide range"],
        prosZh: ["功能广泛"],
        cons: ["Ad-heavy", "Outdated design", "No dark mode"],
        consZh: ["广告多", "设计过时", "无暗黑模式"],
      },
      {
        name: "GoodCalculators",
        url: "#",
        pros: ["Many calculators"],
        prosZh: ["计算器多"],
        cons: ["Slow loading", "Ads", "Limited customization"],
        consZh: ["加载缓慢", "有广告", "定制性有限"],
      },
    ],
    toolboxProAdvantages: [
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
    ],
    toolboxProAdvantagesZh: [
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
      "除浏览器内存外无大小限制",
    ],
  },
  "random-string-generator": {
    toolName: "Random String Generator",
    toolNameZh: "随机字符串生成",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
      "Dark mode support",
    ],
    toolboxProAdvantagesZh: [
      "无需注册或登录",
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
    ],
  },
  "roman-numeral": {
    toolName: "Roman Numeral Converter",
    toolNameZh: "罗马数字转换",
    competitors: [
      {
        name: "Calculator.net",
        url: "#",
        pros: ["Wide range"],
        prosZh: ["功能广泛"],
        cons: ["Ad-heavy", "Outdated design", "No dark mode"],
        consZh: ["广告多", "设计过时", "无暗黑模式"],
      },
      {
        name: "GoodCalculators",
        url: "#",
        pros: ["Many calculators"],
        prosZh: ["计算器多"],
        cons: ["Slow loading", "Ads", "Limited customization"],
        consZh: ["加载缓慢", "有广告", "定制性有限"],
      },
    ],
    toolboxProAdvantages: [
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
    ],
    toolboxProAdvantagesZh: [
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
      "除浏览器内存外无大小限制",
    ],
  },
  "speed-converter": {
    toolName: "Speed Converter",
    toolNameZh: "速度转换器",
    competitors: [
      {
        name: "RapidTables",
        url: "#",
        pros: ["Many unit types"],
        prosZh: ["单位类型多"],
        cons: ["Ad-heavy", "Outdated UI", "No customization"],
        consZh: ["广告多", "界面过时", "不可定制"],
      },
      {
        name: "UnitConverters.net",
        url: "#",
        pros: ["Extensive units"],
        prosZh: ["单位丰富"],
        cons: ["Cluttered interface", "No dark mode", "Sluggish"],
        consZh: ["界面杂乱", "无暗黑模式", "响应迟缓"],
      },
    ],
    toolboxProAdvantages: [
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
    ],
    toolboxProAdvantagesZh: [
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
      "除浏览器内存外无大小限制",
    ],
  },
  "sql-formatter": {
    toolName: "SQL Formatter",
    toolNameZh: "SQL 格式化",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "Dark mode support",
      "Instant results with no server round-trip",
      "Works offline once loaded",
    ],
    toolboxProAdvantagesZh: [
      "支持暗黑模式",
      "即时结果，无服务器往返",
      "加载后可离线使用",
    ],
  },
  "string-escaper": {
    toolName: "String Escaper/Unescaper",
    toolNameZh: "字符串转义工具",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "No file size limits beyond your browser's memory",
      "Dark mode support",
      "Instant results with no server round-trip",
    ],
    toolboxProAdvantagesZh: [
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
      "即时结果，无服务器往返",
    ],
  },
  "svg-to-png": {
    toolName: "SVG to PNG Converter",
    toolNameZh: "SVG 转 PNG",
    competitors: [
      {
        name: "RapidTables",
        url: "#",
        pros: ["Many unit types"],
        prosZh: ["单位类型多"],
        cons: ["Ad-heavy", "Outdated UI", "No customization"],
        consZh: ["广告多", "界面过时", "不可定制"],
      },
      {
        name: "UnitConverters.net",
        url: "#",
        pros: ["Extensive units"],
        prosZh: ["单位丰富"],
        cons: ["Cluttered interface", "No dark mode", "Sluggish"],
        consZh: ["界面杂乱", "无暗黑模式", "响应迟缓"],
      },
    ],
    toolboxProAdvantages: [
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
      "Dark mode support",
    ],
    toolboxProAdvantagesZh: [
      "无需注册或登录",
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
    ],
  },
  "temperature-converter": {
    toolName: "Temperature Converter",
    toolNameZh: "温度转换器",
    competitors: [
      {
        name: "RapidTables",
        url: "#",
        pros: ["Many unit types"],
        prosZh: ["单位类型多"],
        cons: ["Ad-heavy", "Outdated UI", "No customization"],
        consZh: ["广告多", "界面过时", "不可定制"],
      },
      {
        name: "UnitConverters.net",
        url: "#",
        pros: ["Extensive units"],
        prosZh: ["单位丰富"],
        cons: ["Cluttered interface", "No dark mode", "Sluggish"],
        consZh: ["界面杂乱", "无暗黑模式", "响应迟缓"],
      },
    ],
    toolboxProAdvantages: [
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
    ],
    toolboxProAdvantagesZh: [
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
      "除浏览器内存外无大小限制",
    ],
  },
  "text-deduplicator": {
    toolName: "Line Deduplicator",
    toolNameZh: "行去重工具",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
      "Dark mode support",
    ],
    toolboxProAdvantagesZh: [
      "无需注册或登录",
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
    ],
  },
  "text-repeater": {
    toolName: "Text Repeater",
    toolNameZh: "文本重复器",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
    ],
    toolboxProAdvantagesZh: [
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
    ],
  },
  "text-reverser": {
    toolName: "Text Reverser",
    toolNameZh: "文本反转器",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "text-sorter": {
    toolName: "Text Sorter",
    toolNameZh: "文本排序器",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "Dark mode support",
      "Instant results with no server round-trip",
      "Works offline once loaded",
    ],
    toolboxProAdvantagesZh: [
      "支持暗黑模式",
      "即时结果，无服务器往返",
      "加载后可离线使用",
    ],
  },
  "text-statistics": {
    toolName: "Text Statistics",
    toolNameZh: "文本统计分析",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
      "Dark mode support",
    ],
    toolboxProAdvantagesZh: [
      "无需注册或登录",
      "除浏览器内存外无大小限制",
      "支持暗黑模式",
    ],
  },
  "text-to-binary": {
    toolName: "Text to Binary Converter",
    toolNameZh: "文本转二进制",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "text-to-slug": {
    toolName: "Text to URL Slug",
    toolNameZh: "文本转 Slug",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "timezone-converter": {
    toolName: "Time Zone Converter",
    toolNameZh: "时区转换器",
    competitors: [
      {
        name: "Calculator.net",
        url: "#",
        pros: ["Wide range"],
        prosZh: ["功能广泛"],
        cons: ["Ad-heavy", "Outdated design", "No dark mode"],
        consZh: ["广告多", "设计过时", "无暗黑模式"],
      },
      {
        name: "GoodCalculators",
        url: "#",
        pros: ["Many calculators"],
        prosZh: ["计算器多"],
        cons: ["Slow loading", "Ads", "Limited customization"],
        consZh: ["加载缓慢", "有广告", "定制性有限"],
      },
    ],
    toolboxProAdvantages: [
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
    ],
    toolboxProAdvantagesZh: [
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
    ],
  },
  "tip-calculator": {
    toolName: "Tip Calculator",
    toolNameZh: "小费计算器",
    competitors: [
      {
        name: "Calculator.net",
        url: "#",
        pros: ["Wide range"],
        prosZh: ["功能广泛"],
        cons: ["Ad-heavy", "Outdated design", "No dark mode"],
        consZh: ["广告多", "设计过时", "无暗黑模式"],
      },
      {
        name: "GoodCalculators",
        url: "#",
        pros: ["Many calculators"],
        prosZh: ["计算器多"],
        cons: ["Slow loading", "Ads", "Limited customization"],
        consZh: ["加载缓慢", "有广告", "定制性有限"],
      },
    ],
    toolboxProAdvantages: [
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
    ],
    toolboxProAdvantagesZh: [
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
    ],
  },
  "unicode-detector": {
    toolName: "Unicode Character Detector",
    toolNameZh: "Unicode 字符检测",
    competitors: [
      {
        name: "OnlineTextTools.com",
        url: "#",
        pros: ["Variety of text tools"],
        prosZh: ["文本工具丰富"],
        cons: ["Ads everywhere", "Limited batch", "No dark mode"],
        consZh: ["广告泛滥", "批量有限", "无暗黑模式"],
      },
      {
        name: "TextFixer.com",
        url: "#",
        pros: ["Simple"],
        prosZh: ["简单"],
        cons: ["Outdated UI", "Slow processing", "Limited features"],
        consZh: ["界面过时", "处理缓慢", "功能有限"],
      },
    ],
    toolboxProAdvantages: [
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
    ],
    toolboxProAdvantagesZh: [
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
    ],
  },
  "url-encoder-decoder": {
    toolName: "URL Encoder/Decoder",
    toolNameZh: "URL 编码/解码",
    competitors: [
      {
        name: "JSONLint.com",
        url: "#",
        pros: ["Well-known", "Simple interface"],
        prosZh: ["知名度高", "界面简洁"],
        cons: ["Limited features", "No file upload", "Ads heavy"],
        consZh: ["功能有限", "不可上传文件", "广告多"],
      },
      {
        name: "FreeFormatter.com",
        url: "#",
        pros: ["Multiple tools"],
        prosZh: ["多种工具"],
        cons: ["Slow", "Uploads data to server", "Cluttered UI"],
        consZh: ["速度慢", "数据上传服务器", "界面杂乱"],
      },
    ],
    toolboxProAdvantages: [
      "Instant results with no server round-trip",
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
    ],
    toolboxProAdvantagesZh: [
      "即时结果，无服务器往返",
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
    ],
  },
  "weight-converter": {
    toolName: "Weight Converter",
    toolNameZh: "重量转换器",
    competitors: [
      {
        name: "RapidTables",
        url: "#",
        pros: ["Many unit types"],
        prosZh: ["单位类型多"],
        cons: ["Ad-heavy", "Outdated UI", "No customization"],
        consZh: ["广告多", "界面过时", "不可定制"],
      },
      {
        name: "UnitConverters.net",
        url: "#",
        pros: ["Extensive units"],
        prosZh: ["单位丰富"],
        cons: ["Cluttered interface", "No dark mode", "Sluggish"],
        consZh: ["界面杂乱", "无暗黑模式", "响应迟缓"],
      },
    ],
    toolboxProAdvantages: [
      "Works offline once loaded",
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
    ],
    toolboxProAdvantagesZh: [
      "加载后可离线使用",
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
    ],
  },
  "whois-lookup": {
    toolName: "WHOIS Lookup",
    toolNameZh: "WHOIS 查询",
    competitors: [
      {
        name: "MXToolbox",
        url: "#",
        pros: ["Comprehensive"],
        prosZh: ["功能全面"],
        cons: ["Requires signup for some features", "Limited free queries", "Ad-heavy"],
        consZh: ["部分功能需注册", "免费查询有限", "广告多"],
      },
      {
        name: "DNSChecker.org",
        url: "#",
        pros: ["Global DNS lookup"],
        prosZh: ["全球 DNS 查询"],
        cons: ["Limited to DNS only", "No RDAP/WHOIS", "No privacy features"],
        consZh: ["仅限 DNS", "无 RDAP/WHOIS", "无隐私功能"],
      },
    ],
    toolboxProAdvantages: [
      "100% client-side — your data never leaves your browser",
      "No registration or signup required",
      "No file size limits beyond your browser's memory",
    ],
    toolboxProAdvantagesZh: [
      "100%客户端，数据不离浏览器",
      "无需注册或登录",
      "除浏览器内存外无大小限制",
    ],
  },
  "watermark-remover": {
    toolName: "Watermark Remover",
    toolNameZh: "去水印",
    competitors: [
      {
        name: "Inpaint",
        url: "https://theinpaint.com",
        pros: ["Good quality results", "Multiple removal modes"],
        prosZh: ["效果良好", "多种去除模式"],
        cons: ["Uploads images to server", "Free tier adds watermark", "Limited free uses per month"],
        consZh: ["图片上传服务器", "免费版加水印", "每月免费次数有限"],
      },
      {
        name: "Apowersoft Watermark Remover",
        url: "https://apowersoft.com",
        pros: ["Batch processing", "Desktop app available"],
        prosZh: ["批量处理", "桌面版可用"],
        cons: ["Requires installation", "Paid software", "Server-side processing"],
        consZh: ["需安装", "付费软件", "服务器端处理"],
      },
    ],
    toolboxProAdvantages: [
      "100% free — no premium paywall",
      "Files never leave your browser (complete privacy)",
      "Bilingual interface (English & Chinese)",
    ],
    toolboxProAdvantagesZh: [
      "完全免费，无付费墙",
      "文件不离开浏览器，完全私密",
      "中英双语界面",
    ],
  },
  "ocr-text-recognition": {
    toolName: "OCR Text Recognition",
    toolNameZh: "OCR文字识别",
    competitors: [
      {
        name: "OnlineOCR.net",
        url: "https://onlineocr.net",
        pros: ["Multiple languages", "Batch upload"],
        prosZh: ["多语言支持", "批量上传"],
        cons: ["Uploads files to server", "Registration required for large files", "Privacy concerns"],
        consZh: ["文件上传服务器", "大文件需注册", "隐私隐患"],
      },
      {
        name: "Google Drive OCR",
        url: "https://drive.google.com",
        pros: ["High accuracy", "Cloud storage integration"],
        prosZh: ["精度高", "云存储集成"],
        cons: ["Requires Google account", "Uploads to Google servers", "No language selection control"],
        consZh: ["需 Google 账号", "上传至 Google 服务器", "无法选择语言"],
      },
    ],
    toolboxProAdvantages: [
      "100% client-side — documents never leave your device",
      "Completely free with no usage limits",
      "Bilingual interface supporting Chinese and English recognition",
    ],
    toolboxProAdvantagesZh: [
      "100%客户端，文档不离设备",
      "完全免费，无使用限制",
      "中英双语界面，支持中英文识别",
    ],
  },
  "csv-visualizer": {
    toolName: "CSV Data Visualizer",
    toolNameZh: "CSV数据可视化",
    competitors: [
      {
        name: "RAWGraphs",
        url: "https://rawgraphs.io",
        pros: ["Many chart types", "Open source"],
        prosZh: ["图表类型多", "开源"],
        cons: ["Uploads data to server", "Steep learning curve", "No Chinese language support"],
        consZh: ["数据上传服务器", "学习曲线陡", "无中文支持"],
      },
      {
        name: "Datawrapper",
        url: "https://datawrapper.de",
        pros: ["Professional charts", "Publish-ready output"],
        prosZh: ["专业图表", "出版级输出"],
        cons: ["Free tier limited to 10 charts", "Requires account", "Server-side processing"],
        consZh: ["免费版限 10 图表", "需要注册", "服务器端处理"],
      },
    ],
    toolboxProAdvantages: [
      "Free with no chart limits",
      "Data stays on your device — no uploads",
      "Bilingual interface (English & Chinese) with instant rendering",
    ],
    toolboxProAdvantagesZh: [
      "免费无图表数量限制",
      "数据保留在本地，不上传",
      "中英双语界面，即时渲染",
    ],
  },
  "video-to-gif": {
    toolName: "Video to GIF Converter",
    toolNameZh: "视频转GIF",
    competitors: [
      {
        name: "EZGIF",
        url: "https://ezgif.com",
        pros: ["Popular", "Many editing tools"],
        prosZh: ["受欢迎", "编辑工具多"],
        cons: ["Uploads video to server", "50MB file limit", "Ad-heavy interface"],
        consZh: ["视频上传服务器", "限 50MB", "广告多"],
      },
      {
        name: "Giphy",
        url: "https://giphy.com",
        pros: ["Social sharing", "Large library"],
        prosZh: ["社交分享", "资源库大"],
        cons: ["Requires account", "Uploads to public platform", "Privacy concerns"],
        consZh: ["需要注册", "上传至公开平台", "隐私隐患"],
      },
    ],
    toolboxProAdvantages: [
      "Completely free with no file size paywall",
      "Videos never leave your browser",
      "Bilingual interface with precise timeline editing",
    ],
    toolboxProAdvantagesZh: [
      "完全免费，无文件大小付费墙",
      "视频不离开浏览器",
      "中英双语界面，精确时间轴编辑",
    ],
  },
  "markdown-to-pdf": {
    toolName: "Markdown to PDF Converter",
    toolNameZh: "Markdown转PDF",
    competitors: [
      {
        name: "Dillinger",
        url: "https://dillinger.io",
        pros: ["Clean interface", "Cloud sync"],
        prosZh: ["界面清爽", "云同步"],
        cons: ["Uploads content to server", "Limited export formats on free tier", "Requires account for PDF export"],
        consZh: ["内容上传服务器", "免费版导出受限", "PDF导出需注册"],
      },
      {
        name: "MDtoPDF",
        url: "https://mdtopdf.up.railway.app",
        pros: ["Simple to use", "Fast conversion"],
        prosZh: ["简单易用", "转换快速"],
        cons: ["Server-side processing", "Privacy concerns", "Limited customization options"],
        consZh: ["服务器端处理", "隐私隐患", "定制选项有限"],
      },
    ],
    toolboxProAdvantages: [
      "100% free PDF export — no premium tiers",
      "Documents never leave your browser",
      "Bilingual support with customizable professional themes",
    ],
    toolboxProAdvantagesZh: [
      "免费 PDF 导出，无高级付费",
      "文档不离开浏览器",
      "双语支持，可定制专业主题",
    ],
  },
};

export function getToolComparison(slug: string): ToolComparison | undefined {
  return comparisons[slug];
}

export function getAllComparisonSlugs(): string[] {
  return Object.keys(comparisons);
}
