export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: "developer" | "text" | "image" | "pdf" | "audio" | "network" | "conversion" | "utilities";
  icon: string;
  searchKeywords: string;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
}

export const tools: Tool[] = [
  // === Developer Tools (10) ===
  {
    slug: "json-formatter",
    name: "JSON Formatter & Validator",
    description: "Format, validate, and beautify JSON in seconds",
    category: "developer",
    icon: "{}",
    searchKeywords: "json formatter json validator prettify json",
  },
  {
    slug: "base64-encode-decode",
    name: "Base64 Encoder/Decoder",
    description: "Encode text or files to Base64 and decode back",
    category: "developer",
    icon: "B64",
    searchKeywords: "base64 encode decode base64 converter",
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions with real-time highlighting",
    category: "developer",
    icon: ".*",
    searchKeywords: "regex tester regular expression test online",
  },
  {
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert between HEX, RGB, HSL, and more",
    category: "developer",
    icon: "#",
    searchKeywords: "color converter hex to rgb rgb to hex color picker",
  },
  {
    slug: "url-encoder-decoder",
    name: "URL Encoder/Decoder",
    description: "Encode and decode URL components instantly",
    category: "developer",
    icon: "URL",
    searchKeywords: "url encoder url decoder percent encoding",
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs v4 for unique identifiers",
    category: "developer",
    icon: "ID",
    searchKeywords: "uuid generator guid generator unique id",
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Create strong, secure passwords with custom options",
    category: "utilities",
    icon: "🔑",
    searchKeywords: "password generator strong password random password",
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes",
    category: "developer",
    icon: "#H",
    searchKeywords: "hash generator md5 sha256 sha1 sha512 hash online",
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates",
    category: "developer",
    icon: "⏱",
    searchKeywords: "timestamp converter unix timestamp epoch converter",
  },
  {
    slug: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert between binary, octal, decimal, and hexadecimal",
    category: "developer",
    icon: "0x",
    searchKeywords: "binary converter hex converter decimal octal base converter",
  },
  // === Image Tools (3) ===
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Compress images without losing quality",
    category: "image",
    icon: "🖼",
    searchKeywords: "image compressor compress jpg png webp",
  },
  {
    slug: "image-converter",
    name: "Image Format Converter",
    description: "Convert images between JPG, PNG, WebP, and more",
    category: "image",
    icon: "↔",
    searchKeywords: "image converter jpg to png png to webp",
  },
  // === PDF Tools (1) ===
  {
    slug: "pdf-merger",
    name: "PDF Merger",
    description: "Merge multiple PDFs into one document",
    category: "pdf",
    icon: "📄",
    searchKeywords: "pdf merger combine pdf merge pdf files",
  },
  // === Text Tools (4) ===
  {
    slug: "word-counter",
    name: "Word & Character Counter",
    description: "Count words, characters, sentences, and reading time",
    category: "text",
    icon: "Wc",
    searchKeywords: "word counter character counter word count",
  },
  {
    slug: "case-converter",
    name: "Text Case Converter",
    description: "Convert text between UPPER, lower, Title, camelCase and more",
    category: "text",
    icon: "Aa",
    searchKeywords: "case converter uppercase lowercase title case camel case",
  },
  {
    slug: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text for mockups and designs",
    category: "text",
    icon: "¶",
    searchKeywords: "lorem ipsum generator placeholder text dummy text",
  },
  {
    slug: "text-diff-checker",
    name: "Text Diff Checker",
    description: "Compare two texts and highlight the differences",
    category: "text",
    icon: "±",
    searchKeywords: "text diff checker compare text difference online",
  },
  {
    slug: "text-repeater",
    name: "Text Repeater",
    description: "Repeat text multiple times with custom separators",
    category: "text",
    icon: "↻",
    searchKeywords: "text repeater repeat text multiple times string generator",
  },
  // === Conversion Tools (2) ===
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Create custom QR codes for URLs, text, WiFi, and more",
    category: "conversion",
    icon: "▦",
    searchKeywords: "qr code generator create qr code qr maker",
  },
  {
    slug: "html-entity-converter",
    name: "HTML Entity Converter",
    description: "Encode and decode HTML entities like &amp; and &lt;",
    category: "conversion",
    icon: "&lt;",
    searchKeywords: "html entity encoder html entity decoder html escape",
  },
  // === ADDITIONAL Developer Tools (12) ===
  {
    slug: "css-minifier",
    name: "CSS Minifier",
    description: "Minify and compress CSS code to reduce file size",
    category: "developer",
    icon: "CSS",
    searchKeywords: "css minifier css compressor css minify online",
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries for better readability",
    category: "developer",
    icon: "SQL",
    searchKeywords: "sql formatter sql beautifier format sql query",
  },
  {
    slug: "json-to-yaml",
    name: "JSON to YAML Converter",
    description: "Convert JSON data to YAML format and vice versa",
    category: "developer",
    icon: "JY",
    searchKeywords: "json to yaml yaml to json converter online",
  },
  {
    slug: "string-escaper",
    name: "String Escaper/Unescaper",
    description: "Escape and unescape special characters in strings",
    category: "developer",
    icon: "\\n",
    searchKeywords: "string escaper unescape text escape special characters",
  },
  {
    slug: "html-tag-stripper",
    name: "HTML Tag Stripper",
    description: "Remove all HTML tags from text, keeping only content",
    category: "developer",
    icon: "</>",
    searchKeywords: "html tag remover strip html tags remove html",
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode JWT tokens and inspect header, payload, and signature",
    category: "developer",
    icon: "JWT",
    searchKeywords: "jwt decoder jwt debug decode jwt token online",
  },
  {
    slug: "cron-parser",
    name: "Cron Expression Parser",
    description: "Parse cron expressions and get human-readable schedules",
    category: "developer",
    icon: "⏰",
    searchKeywords: "cron expression parser cron explainer cron schedule",
  },
  {
    slug: "text-to-binary",
    name: "Text to Binary Converter",
    description: "Convert text to binary code and binary back to text",
    category: "text",
    icon: "01",
    searchKeywords: "text to binary binary to text converter online",
  },
  {
    slug: "html-preview",
    name: "HTML Preview",
    description: "Write and preview HTML code in real-time in a sandbox",
    category: "developer",
    icon: "</>",
    searchKeywords: "html preview html viewer html render online",
  },
  {
    slug: "csv-viewer",
    name: "CSV Viewer & Formatter",
    description: "View CSV data in a formatted table with auto-detection",
    category: "developer",
    icon: "CSV",
    searchKeywords: "csv viewer csv formatter csv table online",
  },
  {
    slug: "ip-calculator",
    name: "IP Subnet Calculator",
    description: "Calculate network subnet, CIDR, broadcast, and host range",
    category: "developer",
    icon: "IP",
    searchKeywords: "ip subnet calculator cidr calculator network calculator",
  },
  {
    slug: "jwt-generator",
    name: "JWT Generator",
    description: "Generate JWT tokens with custom header and payload",
    category: "developer",
    icon: "🔐",
    searchKeywords: "jwt generator create jwt token json web token",
  },
  // === ADDITIONAL Text Tools (7) ===
  {
    slug: "text-to-slug",
    name: "Text to URL Slug",
    description: "Convert text into clean, SEO-friendly URL slugs",
    category: "text",
    icon: "🔗",
    searchKeywords: "url slug generator text to slug seo friendly url",
  },
  {
    slug: "text-sorter",
    name: "Text Sorter",
    description: "Sort lines alphabetically, reverse, or by length",
    category: "text",
    icon: "AZ",
    searchKeywords: "text sorter sort lines alphabetically online",
  },
  {
    slug: "text-deduplicator",
    name: "Line Deduplicator",
    description: "Remove duplicate lines from text while preserving order",
    category: "text",
    icon: "==-",
    searchKeywords: "remove duplicate lines deduplicate text online",
  },
  {
    slug: "text-reverser",
    name: "Text Reverser",
    description: "Reverse text, words, or lines instantly",
    category: "text",
    icon: "↩",
    searchKeywords: "text reverser reverse string reverse words online",
  },
  {
    slug: "random-string-generator",
    name: "Random String Generator",
    description: "Generate random strings with custom characters and length",
    category: "text",
    icon: "RNG",
    searchKeywords: "random string generator random text online",
  },
  {
    slug: "palindrome-checker",
    name: "Palindrome Checker",
    description: "Check if text reads the same forwards and backwards",
    category: "text",
    icon: "🔄",
    searchKeywords: "palindrome checker palindrome test online",
  },
  {
    slug: "morse-code-converter",
    name: "Morse Code Converter",
    description: "Convert text to Morse code and Morse code to text",
    category: "text",
    icon: "•-",
    searchKeywords: "morse code converter text to morse morse to text",
  },
  // === ADDITIONAL Conversion Tools (6) ===
  {
    slug: "temperature-converter",
    name: "Temperature Converter",
    description: "Convert between Celsius, Fahrenheit, and Kelvin",
    category: "conversion",
    icon: "🌡",
    searchKeywords: "temperature converter celsius fahrenheit kelvin",
  },
  {
    slug: "weight-converter",
    name: "Weight Converter",
    description: "Convert between kilograms, pounds, ounces, and more",
    category: "conversion",
    icon: "⚖",
    searchKeywords: "weight converter kg to lbs pounds converter online",
  },
  {
    slug: "length-converter",
    name: "Length Converter",
    description: "Convert between meters, feet, inches, kilometers, and miles",
    category: "conversion",
    icon: "📏",
    searchKeywords: "length converter meters to feet inches cm converter",
  },
  {
    slug: "data-size-converter",
    name: "Data Size Converter",
    description: "Convert between bytes, KB, MB, GB, TB, and more",
    category: "conversion",
    icon: "💾",
    searchKeywords: "data size converter mb to gb bytes converter online",
  },
  {
    slug: "speed-converter",
    name: "Speed Converter",
    description: "Convert between km/h, mph, knots, m/s and more",
    category: "conversion",
    icon: "🚀",
    searchKeywords: "speed converter kmh to mph knots converter online",
  },
  {
    slug: "area-converter",
    name: "Area Converter",
    description: "Convert between square meters, acres, hectares, sq ft",
    category: "conversion",
    icon: "▣",
    searchKeywords: "area converter square meters to acres hectares online",
  },
  // === ADDITIONAL Image Tools (2) ===
  {
    slug: "image-to-base64",
    name: "Image to Base64",
    description: "Convert images to Base64 data URI for inline embedding",
    category: "image",
    icon: "🖼",
    searchKeywords: "image to base64 image to data uri base64 image converter",
  },
  {
    slug: "random-number-generator",
    name: "Random Number Generator",
    description: "Generate random numbers within a custom range",
    category: "utilities",
    icon: "🎲",
    searchKeywords: "random number generator random number online",
  },
  // === PDF Tools (5 new) ===
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert images (JPG, PNG) into a single PDF document",
    category: "pdf",
    icon: "🖼➔📄",
    searchKeywords: "image to pdf jpg to pdf png to pdf converter",
  },
  {
    slug: "pdf-splitter",
    name: "PDF Splitter",
    description: "Split PDF by page ranges or extract specific pages",
    category: "pdf",
    icon: "✂️",
    searchKeywords: "pdf splitter split pdf extract pages online",
  },
  {
    slug: "pdf-rotator",
    name: "PDF Rotator",
    description: "Rotate PDF pages by 90, 180, or 270 degrees",
    category: "pdf",
    icon: "🔄",
    searchKeywords: "pdf rotator rotate pdf pages online",
  },
  {
    slug: "pdf-page-remover",
    name: "PDF Page Remover",
    description: "Remove unwanted pages from your PDF documents",
    category: "pdf",
    icon: "🗑",
    searchKeywords: "pdf page remover delete pdf pages online",
  },
  // === NEW Image Tools (5) ===
  {
    slug: "image-cropper",
    name: "Image Cropper",
    description: "Crop images by dragging a selection area on canvas",
    category: "image",
    icon: "✂️",
    searchKeywords: "image cropper crop image online free",
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Resize images to exact dimensions with aspect ratio lock",
    category: "image",
    icon: "📐",
    searchKeywords: "image resizer resize image online dimensions",
  },
  {
    slug: "image-filters",
    name: "Image Filters",
    description: "Apply grayscale, sepia, blur, brightness, and contrast filters",
    category: "image",
    icon: "🎨",
    searchKeywords: "image filters photo effects grayscale sepia online",
  },
  {
    slug: "color-picker",
    name: "Color Picker from Image",
    description: "Pick colors from uploaded images or use the color selector",
    category: "image",
    icon: "🎯",
    searchKeywords: "color picker from image eyedropper online",
  },
  {
    slug: "gif-maker",
    name: "GIF Maker",
    description: "Create animated GIFs from multiple images",
    category: "image",
    icon: "🎞",
    searchKeywords: "gif maker create gif from images animated online",
  },
  // === MORE Image Tools (7) ===
  {
    slug: "image-watermark",
    name: "Image Watermark",
    description: "Add text watermark to images with position and opacity control",
    category: "image",
    icon: "💧",
    searchKeywords: "image watermark add watermark to photo online",
  },
  {
    slug: "image-merge",
    name: "Image Merger",
    description: "Combine multiple images into one side by side or grid",
    category: "image",
    icon: "⊞",
    searchKeywords: "merge images combine photos side by side online",
  },
  {
    slug: "image-splitter",
    name: "Image Splitter",
    description: "Split an image into tiles by rows and columns",
    category: "image",
    icon: "⊟",
    searchKeywords: "image splitter split image into tiles grid online",
  },
  {
    slug: "image-flip",
    name: "Image Flip & Rotate",
    description: "Flip horizontally, vertically, or rotate images",
    category: "image",
    icon: "🔄",
    searchKeywords: "image flip mirror rotate image horizontally vertically",
  },
  {
    slug: "image-border",
    name: "Image Border",
    description: "Add customizable borders and frames to images",
    category: "image",
    icon: "▫",
    searchKeywords: "image border photo frame add border to image online",
  },
  {
    slug: "meme-generator",
    name: "Meme Generator",
    description: "Create memes by adding top and bottom text to images",
    category: "image",
    icon: "😂",
    searchKeywords: "meme generator create meme add text to image online",
  },
  {
    slug: "image-to-sketch",
    name: "Image to Sketch",
    description: "Convert photos into pencil sketch drawings",
    category: "image",
    icon: "✏️",
    searchKeywords: "image to sketch photo to pencil drawing sketch effect",
  },
  // === NEW Text Tools (3) ===
  {
    slug: "emoji-remover",
    name: "Emoji Remover",
    description: "Remove all emoji characters from text while keeping words",
    category: "text",
    icon: "😊✂️",
    searchKeywords: "emoji remover remove emoji from text online",
  },
  {
    slug: "unicode-detector",
    name: "Unicode Character Detector",
    description: "Inspect Unicode characters with codepoint and category info",
    category: "text",
    icon: "U+",
    searchKeywords: "unicode detector character code codepoint lookup online",
  },
  {
    slug: "caesar-cipher",
    name: "Caesar Cipher",
    description: "Encode and decode text using Caesar shift cipher",
    category: "text",
    icon: "🔐",
    searchKeywords: "caesar cipher encoder decoder shift cipher online",
  },
  // === NEW Developer Tools (3) ===
  {
    slug: "json-diff",
    name: "JSON Diff",
    description: "Compare two JSON objects and highlight differences",
    category: "developer",
    icon: "±J",
    searchKeywords: "json diff compare json objects online",
  },
  {
    slug: "http-status-codes",
    name: "HTTP Status Codes",
    description: "Browse and search all HTTP status codes with descriptions",
    category: "developer",
    icon: "200",
    searchKeywords: "http status codes list 404 500 error codes online",
  },
  {
    slug: "markdown-to-html",
    name: "Markdown to HTML",
    description: "Convert Markdown text to formatted HTML in real-time",
    category: "developer",
    icon: "MD",
    searchKeywords: "markdown to html converter md to html online",
  },
  // === NEW Conversion (2) ===
  {
    slug: "timezone-converter",
    name: "Time Zone Converter",
    description: "Convert time between different world time zones",
    category: "utilities",
    icon: "🌍",
    searchKeywords: "timezone converter time zone converter online",
  },
  {
    slug: "binary-to-text",
    name: "Binary to Text",
    description: "Convert binary code to text and text back to binary",
    category: "text",
    icon: "01T",
    searchKeywords: "binary to text converter binary translator online",
  },
  // === NEW Image Tools (2) ===
  {
    slug: "image-invert",
    name: "Image Invert",
    description: "Invert or negate colors in an image instantly",
    category: "image",
    icon: "🎞",
    searchKeywords: "image invert negative photo colors reverse online",
  },
  {
    slug: "image-collage",
    name: "Photo Collage Maker",
    description: "Combine multiple photos into a beautiful collage",
    category: "image",
    icon: "🖼",
    searchKeywords: "photo collage maker combine pictures online",
  },
  // === NEW Developer Tools (5) ===
  {
    slug: "css-gradient",
    name: "CSS Gradient Generator",
    description: "Create beautiful linear and radial CSS gradients",
    category: "developer",
    icon: "🎨",
    searchKeywords: "css gradient generator linear radial background online",
  },
  {
    slug: "css-shadow",
    name: "CSS Box Shadow Generator",
    description: "Design and preview custom CSS box shadows visually",
    category: "developer",
    icon: "⬡",
    searchKeywords: "css box shadow generator drop shadow online",
  },
  {
    slug: "json-to-typescript",
    name: "JSON to TypeScript",
    description: "Convert JSON objects into TypeScript interfaces",
    category: "developer",
    icon: "TS",
    searchKeywords: "json to typescript interface generator online",
  },
  {
    slug: "html-to-jsx",
    name: "HTML to JSX Converter",
    description: "Convert HTML code into React JSX syntax",
    category: "developer",
    icon: "⚛",
    searchKeywords: "html to jsx converter react html transform online",
  },
  {
    slug: "color-palette",
    name: "Color Palette Generator",
    description: "Generate color schemes: monochromatic, complementary, and more",
    category: "developer",
    icon: "🎨",
    searchKeywords: "color palette generator color scheme designer online",
  },
  // === NEW Everyday Tools (8) ===
  {
    slug: "roman-numeral",
    name: "Roman Numeral Converter",
    description: "Convert between Roman numerals and Arabic numbers",
    category: "utilities",
    icon: "IV",
    searchKeywords: "roman numeral converter number to roman online",
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages, what if, increase/decrease easily",
    category: "utilities",
    icon: "%",
    searchKeywords: "percentage calculator percent of number online",
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    description: "Calculate tip amount, total bill, and per-person cost",
    category: "utilities",
    icon: "💵",
    searchKeywords: "tip calculator restaurant tip split bill online",
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate exact age in years, months, and days",
    category: "utilities",
    icon: "🎂",
    searchKeywords: "age calculator birthday age difference online",
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate Body Mass Index and check your health category",
    category: "utilities",
    icon: "⚕",
    searchKeywords: "bmi calculator body mass index health weight online",
  },
  {
    slug: "countdown-timer",
    name: "Countdown Timer",
    description: "Set a countdown to any date and time",
    category: "utilities",
    icon: "⏱",
    searchKeywords: "countdown timer online days hours minutes seconds",
  },
  {
    slug: "dice-roller",
    name: "Dice Roller",
    description: "Roll virtual dice with various sides (d4 to d20)",
    category: "utilities",
    icon: "🎲",
    searchKeywords: "dice roller virtual dice roll d20 d6 online",
  },
  {
    slug: "decision-maker",
    name: "Decision Maker",
    description: "Let fate decide — pick a random option from your list",
    category: "utilities",
    icon: "❓",
    searchKeywords: "decision maker random picker choice selector online",
  },
  // === Audio Tools (3) ===
  {
    slug: "audio-cutter",
    name: "Audio Cutter",
    description: "Trim and cut audio files with waveform preview",
    category: "audio",
    icon: "🎧",
    searchKeywords: "audio cutter trim mp3 wav online",
  },
  {
    slug: "audio-merger",
    name: "Audio Merger",
    description: "Combine multiple audio files into one track",
    category: "audio",
    icon: "🎤",
    searchKeywords: "audio merger join combine mp3 online",
  },
  {
    slug: "audio-converter",
    name: "Audio Converter",
    description: "Convert audio between WAV formats and sample rates",
    category: "audio",
    icon: "🔊",
    searchKeywords: "audio converter wav mp3 sample rate online",
  },
  // === Network Tools (1) ===
  {
    slug: "dns-lookup",
    name: "DNS Lookup",
    description: "Look up DNS records: A, AAAA, MX, NS, TXT, CNAME",
    category: "network",
    icon: "🌐",
    searchKeywords: "dns lookup dns check domain records online",
  },
  {
    slug: "whois-lookup",
    name: "WHOIS Lookup",
    description: "Look up domain registration and ownership information",
    category: "network",
    icon: "📋",
    searchKeywords: "whois lookup domain registration owner check online",
  },
  // === More Popular Tools (7) ===
  {
    slug: "svg-to-png",
    name: "SVG to PNG Converter",
    description: "Convert SVG code or files to PNG images",
    category: "conversion",
    icon: "🖼",
    searchKeywords: "svg to png converter svg to image online",
  },
  {
    slug: "days-between",
    name: "Days Between Dates",
    description: "Calculate the exact number of days between two dates",
    category: "utilities",
    icon: "📅",
    searchKeywords: "days between dates calculator date difference online",
  },
  {
    slug: "password-strength",
    name: "Password Strength Checker",
    description: "Test how strong your password is with real-time analysis",
    category: "developer",
    icon: "🛡",
    searchKeywords: "password strength checker test secure online",
  },
  {
    slug: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate barcodes in Code128, EAN-13, Code39 formats",
    category: "conversion",
    icon: "▌▌",
    searchKeywords: "barcode generator code128 ean13 code39 online",
  },
  {
    slug: "aspect-ratio-calculator",
    name: "Aspect Ratio Calculator",
    description: "Calculate aspect ratios from dimensions or presets",
    category: "utilities",
    icon: "▬",
    searchKeywords: "aspect ratio calculator 16:9 4:3 resolution online",
  },
  {
    slug: "qr-reader",
    name: "QR Code Reader",
    description: "Decode QR codes from uploaded images",
    category: "conversion",
    icon: "▦",
    searchKeywords: "qr code reader decoder scan qr image online",
  },
  {
    slug: "color-blindness-simulator",
    name: "Color Blindness Simulator",
    description: "Simulate how images look with various color blindness types",
    category: "image",
    icon: "👁",
    searchKeywords: "color blindness simulator protanopia deuteranopia online",
  },
  {
    slug: "online-notepad",
    name: "Online Notepad",
    description: "A simple browser-based notepad with auto-save",
    category: "text",
    icon: "📝",
    searchKeywords: "online notepad text editor notes browser online",
  },
  {
    slug: "text-statistics",
    name: "Text Statistics",
    description: "Detailed text analysis: letters, vowels, unique words, and more",
    category: "text",
    icon: "📊",
    searchKeywords: "text statistics analysis letter frequency word count online",
  },
];

export const categories = [
  { id: "developer" as const, name: "Developer Tools", icon: "⌨️" },
  { id: "text" as const, name: "Text Tools", icon: "✍️" },
  { id: "image" as const, name: "Image Tools", icon: "🖼️" },
  { id: "pdf" as const, name: "PDF Tools", icon: "📄" },
  { id: "audio" as const, name: "Audio Tools", icon: "🎧" },
  { id: "network" as const, name: "Network Tools", icon: "🌐" },
  { id: "conversion" as const, name: "Unit Converters", icon: "📐" },
  { id: "utilities" as const, name: "Utilities", icon: "🧰" },
];

export function getTool(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter((t) => t.category === category);
}
