export const toolGuidesBatch2: Record<string, { en: string; zh: string }> = {
  "text-reverser": {
    en: `Text Reverser is a versatile online text manipulation tool that instantly reverses your text in multiple ways. Whether you need to reverse entire strings, individual words while keeping sentence order, or flip text character by character, this tool handles it all. It is perfect for creating mirrored text for puzzles, checking spelling patterns, generating creative content, or solving word games. Simply paste or type your text into the input field, select your preferred reversal mode — full text reverse, word-level reverse, or sentence-level reverse — and see the result immediately in real time. The tool supports all languages and special characters including emojis, Unicode symbols, and multibyte characters. You can copy the reversed output with one click for instant use elsewhere. All processing happens entirely in your browser, meaning your text data never leaves your device and is never uploaded to any server. This makes it a safe and private solution for reversing sensitive or personal text content.`,
    zh: `文本反转器是一款多功能在线文本处理工具，可即时以多种方式反转您的文本。无论您需要反转整个字符串、保持句子顺序反转单个单词，还是逐字符翻转文本，此工具都能轻松完成。它非常适合为谜题创建镜像文本、检查拼写模式、生成创意内容或解决文字游戏。只需将文本粘贴或输入到输入框中，选择您喜欢的反转模式——全文反转、单词级反转或句子级反转——即可立即看到实时结果。该工具支持所有语言和特殊字符，包括表情符号、Unicode 符号和多字节字符。您可以一键复制反转结果，方便在其他地方使用。所有处理完全在浏览器中进行，这意味着您的文本数据永远不会离开您的设备，也永远不会上传到任何服务器。这使其成为反转敏感或个人文本内容的安全私密解决方案。`,
  },
  "random-string-generator": {
    en: `Random String Generator creates secure, customizable random strings for passwords, API keys, tokens, and test data. Choose your desired length, character set — uppercase letters, lowercase letters, numbers, and special symbols — and generate as many strings as you need in one batch. The tool uses cryptographically strong random generation to ensure each string is unique and unpredictable, making it ideal for password creation, session tokens, database IDs, and programming test fixtures. You can customize the exact mix of characters, exclude ambiguous characters like zero and capital O, and set a minimum number of uppercase letters or digits for compliance requirements. Generated strings can be copied individually or exported as a list for batch use. Every generation happens locally in your browser using the Web Crypto API, so no string data is transmitted to any external server. Your generated passwords and tokens remain completely private and secure on your own device.`,
    zh: `随机字符串生成器可创建安全、可自定义的随机字符串，适用于密码、API 密钥、令牌和测试数据。选择所需的长度、字符集——大写字母、小写字母、数字和特殊符号——并一次批量生成所需数量的字符串。该工具使用加密级强随机生成，确保每个字符串唯一且不可预测，非常适合创建密码、会话令牌、数据库 ID 和编程测试用例。您可以自定义字符的精确组合，排除容易混淆的字符如零和大写 O，并为合规要求设置大写字母或数字的最少数量。生成的字符串可以单独复制或导出为列表供批量使用。所有生成过程均在浏览器本地使用 Web Crypto API 完成，不会将任何字符串数据传输到外部服务器。您生成的密码和令牌完全保持私密，安全地保存在您自己的设备上。`,
  },
  "palindrome-checker": {
    en: `Palindrome Checker instantly verifies whether a given text is a palindrome — a word, phrase, or sequence that reads the same forwards and backwards. This tool is essential for word game enthusiasts, puzzle solvers, and language learners who want to test words like "racecar" or phrases like "A man, a plan, a canal: Panama." Simply type or paste your text and the checker will analyze it in real time, ignoring spaces, punctuation, capitalization, and special characters to determine if the core text forms a palindrome. It shows you a detailed breakdown of the analysis, displaying the original text alongside the cleaned version so you can see exactly how the check was performed. The tool supports all languages including Chinese, Japanese, Arabic, and other scripts where palindromes may have cultural significance. All analysis occurs entirely in your browser without any data being sent to servers, ensuring your input remains completely private and secure.`,
    zh: `回文检测器可即时验证给定文本是否为回文——即正读和倒读相同的单词、短语或序列。此工具对于文字游戏爱好者、谜题解答者和语言学习者至关重要，用于测试如 "racecar" 这样的单词或如 "A man, a plan, a canal: Panama" 这样的短语。只需输入或粘贴文本，检测器就会实时分析，忽略空格、标点符号、大小写和特殊字符，以确定核心文本是否构成回文。它会显示分析的详细分解，将原始文本与清理后的版本并列展示，让您清楚了解检测过程。该工具支持所有语言，包括中文、日文、阿拉伯文和其他可能具有文化意义的回文脚本。所有分析完全在浏览器中进行，不会将任何数据发送到服务器，确保您的输入完全私密安全。`,
  },
  "morse-code-converter": {
    en: `Morse Code Converter translates text to Morse code and decodes Morse code back into readable text, making it an essential tool for radio enthusiasts, history buffs, and anyone curious about this classic communication system. The tool supports full bidirectional conversion — type any text to see its dot-and-dash equivalent, or input Morse code patterns to decode them into plain text. It displays the international Morse code alphabet reference so you can learn the system while using it. Each character is clearly separated with standard spacing rules, and the tool handles letters, numbers, and common punctuation marks. You can copy the converted output with one click for easy sharing or documentation. The converter runs entirely in your browser using local processing, ensuring that any messages you encode or decode remain completely private. Whether you are studying for a ham radio license, creating themed content, or simply exploring this fascinating encoding system, this tool provides instant and accurate Morse code translation.`,
    zh: `莫尔斯电码转换器可将文本转换为莫尔斯电码，并将莫尔斯电码解码回可读文本，是无线电爱好者、历史爱好者和任何对这一经典通信系统感兴趣的人的必备工具。该工具支持完全双向转换——输入任何文本即可看到其点划等效代码，或输入莫尔斯电码模式即可将其解码为纯文本。它显示国际莫尔斯电码字母表参考，让您在使用的同时学习该系统。每个字符都使用标准间距规则清晰分隔，该工具支持字母、数字和常用标点符号。您可以一键复制转换后的输出，方便分享或文档记录。转换器完全在浏览器中运行，使用本地处理，确保您编码或解码的任何消息完全保持私密。无论您是在准备业余无线电执照考试、创建主题内容，还是仅仅探索这个迷人的编码系统，此工具都能提供即时准确的莫尔斯电码翻译。`,
  },
  "temperature-converter": {
    en: `Temperature Converter is an instant, precise tool for converting temperatures between Celsius, Fahrenheit, and Kelvin scales. Whether you are following a recipe from another country, checking weather reports abroad, conducting scientific experiments, or studying thermodynamics, this converter handles all three major temperature scales with ease. Simply enter a value in any field and all other scales update simultaneously in real time. The tool also displays a reference chart showing common temperature milestones like the freezing and boiling points of water across all three scales for quick comparison. It supports decimal precision for accurate scientific calculations and handles both positive and negative values. The clean interface makes conversions effortless even for large or small temperature ranges. All computations happen locally in your browser with no data sent to external servers, so your usage is completely private. This free online temperature converter is accessible on any device and requires no registration or software installation.`,
    zh: `温度转换器是一款即时、精确的工具，用于在摄氏度、华氏度和开尔文温标之间转换温度。无论您是在按照其他国家的食谱烹饪、查看国外天气预报、进行科学实验还是学习热力学，此转换器都能轻松处理所有三种主要温标。只需在任意字段中输入一个数值，其他温标即可同时实时更新。该工具还显示参考图表，展示三种温标下常见温度里程碑（如水的冰点和沸点），方便快速比较。它支持小数精度，适合精确的科学计算，并能处理正负值。简洁的界面使转换操作轻松便捷，即使处理极大或极小的温度范围也不在话下。所有计算完全在浏览器本地进行，不发送任何数据到外部服务器，因此您的使用完全私密。这款免费在线温度转换器可在任何设备上使用，无需注册或安装软件。`,
  },
  "weight-converter": {
    en: `Weight Converter provides fast and accurate conversions between kilograms, grams, pounds, ounces, stones, and tons. This versatile tool is invaluable for cooking international recipes, managing fitness goals, calculating shipping costs, or comparing product weights across different measurement systems. Simply enter a weight value in any unit field and see the equivalent values in all other units update instantly in real time. The converter supports both metric and imperial systems, handling everything from tiny fractions of an ounce to massive tonnage values with precision. The intuitive interface lets you input values of any size and automatically converts them across all supported weight units simultaneously. Whether you are a home cook converting recipe measurements, a gym enthusiast tracking body weight in different units, or a logistics professional working with international shipments, this tool delivers instant results. All conversions are computed locally in your browser, ensuring your data never leaves your device and your usage remains completely private.`,
    zh: `重量转换器提供千克、克、磅、盎司、英石和吨之间的快速精确转换。这款多功能工具对于烹饪国际食谱、管理健身目标、计算运费或比较不同计量系统的产品重量非常宝贵。只需在任意单位字段中输入一个重量值，即可即时查看所有其他单位的等效值更新。转换器支持公制和英制系统，从微小的几分之一盎司到巨大的吨级数值都能精确处理。直观的界面让您输入任意大小的数值，并同时自动将它们转换为所有支持的重量单位。无论您是将食谱计量单位进行换算的家庭厨师、以不同单位跟踪体重的健身爱好者，还是处理国际货物的物流专业人士，此工具都能即时交付结果。所有转换都在浏览器本地计算，确保您的数据永远不会离开您的设备，您的使用完全保持私密。`,
  },
  "length-converter": {
    en: `Length Converter is a comprehensive measurement tool that instantly converts between meters, centimeters, millimeters, kilometers, inches, feet, yards, miles, and nautical miles. Whether you are working on a construction project, following an international recipe, planning a trip, or studying physics, this converter makes switching between metric and imperial length units effortless. Enter any value in any field and watch all other unit equivalents update simultaneously in real time. The tool supports extreme precision for engineering calculations and handles values from microscopic measurements to astronomical distances. It also displays a helpful reference for common conversions like the relationship between inches and centimeters. The clean, responsive interface works perfectly on both desktop and mobile devices, making it accessible anywhere you need quick length conversions. All calculations are performed locally in your browser without any data being transmitted to external servers, guaranteeing complete privacy for every measurement you enter.`,
    zh: `长度转换器是一款全面的测量工具，可在米、厘米、毫米、千米、英寸、英尺、码、英里和海里之间即时转换。无论您是在进行建筑项目、遵循国际食谱、规划旅行还是学习物理，此转换器都能让公制和英制长度单位之间的切换变得毫不费力。在任意字段中输入任何值，即可同时查看所有其他单位的等效值更新。该工具支持极高精度的工程计算，并能处理从微观测量到天文距离的数值。它还显示常见换算的有用参考，如英寸和厘米之间的关系。简洁、响应式的界面在桌面和移动设备上都能完美运行，使您在任何需要快速长度换算的地方都能方便使用。所有计算完全在浏览器本地进行，不会有任何数据传输到外部服务器，保证您输入的每个测量数据完全私密。`,
  },
  "data-size-converter": {
    en: `Data Size Converter helps you instantly convert between bytes, kilobytes, megabytes, gigabytes, terabytes, petabytes, and their binary equivalents like kibibytes, mebibytes, and gibibytes. This essential developer and IT tool makes it simple to compare file sizes, storage capacities, and data transfer rates across different measurement systems. Enter a value in any field and see all other units update immediately in real time. The tool distinguishes between decimal (SI) and binary (IEC) measurement standards, which is crucial for accurate storage calculations since manufacturers and operating systems often use different conventions. Whether you are checking if a file fits on a USB drive, calculating cloud storage costs, converting network bandwidth specifications, or planning database sizes, this converter provides precise results instantly. It handles values from tiny bytes to enormous exabytes with full decimal precision. All processing happens locally in your browser, so no data about your file sizes or storage calculations is ever sent to external servers, keeping your information completely private.`,
    zh: `数据大小转换器帮助您在字节、千字节、兆字节、吉字节、太字节、拍字节及其二进制等效单位（如 KiB、MiB、GiB）之间即时转换。这款对开发者和 IT 人员至关重要的工具，使不同计量系统之间的文件大小、存储容量和数据传输速率比较变得简单。在任意字段中输入一个值，即可立即查看所有其他单位的实时更新。该工具区分十进制（SI）和二进制（IEC）计量标准，这对于精确的存储计算至关重要，因为制造商和操作系统通常使用不同的约定。无论您是在检查文件是否适合 USB 驱动器、计算云存储费用、转换网络带宽规格还是规划数据库大小，此转换器都能即时提供精确结果。它能处理从微小的字节到巨大的艾字节的所有数值，具有完整的小数精度。所有处理完全在浏览器本地进行，因此关于您文件大小或存储计算的数据永远不会发送到外部服务器，保持您的信息完全私密。`,
  },
  "speed-converter": {
    en: `Speed Converter instantly translates speed measurements between kilometers per hour, miles per hour, meters per second, knots, and Mach numbers. This versatile tool is essential for drivers, pilots, sailors, athletes, and students who need to work with speed values across different measurement systems. Whether you are converting a car speedometer reading from km/h to mph for international driving, calculating wind speed in knots for aviation, or comparing athletic performance records set in different units, this converter handles it all with precision. Enter any speed value in one unit and see all other unit equivalents update immediately in real time. The tool supports decimal precision for technical calculations and handles both everyday speeds and extreme values like Mach speeds for aerospace applications. The clean interface includes common speed reference points for quick mental comparisons. All conversions are performed entirely in your browser, ensuring that no speed data or calculation details are transmitted to external servers, keeping your usage fully private and secure.`,
    zh: `速度转换器可在千米/时、英里/时、米/秒、节和马赫数之间即时转换速度测量值。这款多功能工具对于需要在不同计量系统中处理速度值的驾驶员、飞行员、水手、运动员和学生来说必不可少。无论您是在为国际驾驶将汽车速度表读数从千米/时转换为英里/时、为航空计算以节为单位的风速，还是比较以不同单位设置的运动表现记录，此转换器都能精确处理。在一个单位中输入任何速度值，即可立即看到所有其他单位等效值的更新。该工具支持技术计算的小数精度，能处理日常速度和极端值（如航空航天应用的马赫速度）。简洁的界面包含常见速度参考点，方便快速心算比较。所有转换完全在浏览器中进行，确保不会有任何速度数据或计算详情传输到外部服务器，使您的使用完全私密安全。`,
  },
  "area-converter": {
    en: `Area Converter provides instant conversions between square meters, square feet, square inches, square kilometers, square miles, acres, hectares, and square yards. This essential tool serves real estate professionals, farmers, architects, students, and anyone who needs to compare land areas or room sizes across different measurement systems. Simply enter a value in any unit field and watch all other area equivalents update simultaneously in real time. The converter handles both metric and imperial area measurements with full decimal precision, making it perfect for calculating property sizes, comparing lot dimensions between countries, planning garden layouts, or estimating material quantities for construction projects. The intuitive interface displays common reference areas like a football field or basketball court for scale context. Whether you are buying property internationally, estimating paint coverage for a room, or converting farmland measurements, this tool delivers accurate results instantly. All area calculations are performed locally in your browser without any data being sent to external servers, ensuring complete privacy for all your measurements.`,
    zh: `面积转换器提供平方米、平方英尺、平方英寸、平方千米、平方英里、英亩、公顷和平方码之间的即时转换。这款必备工具服务于房地产专业人士、农民、建筑师、学生以及任何需要跨不同计量系统比较土地面积或房间大小的人。只需在任意单位字段中输入一个值，即可同时查看所有其他面积等效值的更新。转换器以完整的小数精度处理公制和英亩面积测量，非常适合计算房产面积、比较不同国家的地块尺寸、规划花园布局或估算建筑材料数量。直观的界面显示常见参考面积，如足球场或篮球场作为比例参考。无论您是在国际上购买房产、估算房间的油漆覆盖面积，还是转换农田测量数据，此工具都能即时提供准确结果。所有面积计算完全在浏览器本地进行，不会将任何数据发送到外部服务器，确保您所有测量数据的完全隐私。`,
  },
  "image-to-base64": {
    en: `Image to Base64 converts any image file into a Base64 encoded data URI string that can be embedded directly into HTML, CSS, JavaScript, and other code. This developer-friendly tool is perfect for creating inline images in email templates, embedding small images without separate file hosting, generating data URIs for web applications, and simplifying deployment by reducing external file dependencies. Simply drag and drop or select an image — supporting JPG, PNG, GIF, WebP, SVG, and BMP formats — and the tool instantly generates the complete Base64 string along with the proper MIME type header. You can copy the full data URI or just the encoded string with one click. The tool also shows the original and encoded file sizes so you can assess the size impact of Base64 encoding. For privacy-conscious users, all image processing and encoding happens entirely within your browser using the FileReader API. Your image data is never uploaded to any server, making this a completely secure solution for handling sensitive images.`,
    zh: `Image to Base64 可将任何图像文件转换为 Base64 编码的数据 URI 字符串，可直接嵌入 HTML、CSS、JavaScript 和其他代码中。这款对开发者友好的工具非常适合在电子邮件模板中创建内联图像、在无需单独文件托管的情况下嵌入小型图像、为 Web 应用生成数据 URI，以及通过减少外部文件依赖来简化部署。只需拖放或选择图像——支持 JPG、PNG、GIF、WebP、SVG 和 BMP 格式——工具即可即时生成完整的 Base64 字符串及正确的 MIME 类型头。您可以一键复制完整的数据 URI 或仅复制编码字符串。该工具还显示原始和编码后的文件大小，以便您评估 Base64 编码的大小影响。对于注重隐私的用户，所有图像处理和编码完全在浏览器内使用 FileReader API 完成。您的图像数据永远不会上传到任何服务器，使其成为处理敏感图像的完全安全解决方案。`,
  },
  "random-number-generator": {
    en: `Random Number Generator produces truly random numbers within any custom range you specify, making it ideal for lotteries, giveaways, statistical sampling, game development, and educational activities. Set your minimum and maximum values, choose how many numbers to generate, and optionally allow or exclude duplicates. The tool uses cryptographically secure randomness via the Web Crypto API to ensure each result is genuinely unpredictable and fair. You can generate single numbers or batches of hundreds at once, with options to sort results in ascending or descending order. The clean output makes it easy to copy individual numbers or export the entire list for use in spreadsheets, databases, or applications. Whether you are picking contest winners, creating test data, making random selections for research studies, or building game mechanics that need fair randomness, this generator delivers reliable results. All number generation happens locally in your browser using secure cryptographic methods, meaning no random seeds or generated values are ever transmitted to external servers, keeping your results completely private.`,
    zh: `随机数字生成器在您指定的任何自定义范围内生成真正的随机数，非常适合抽奖、赠品活动、统计采样、游戏开发和教育活动。设置最小值和最大值，选择要生成的数字数量，并可选择允许或排除重复项。该工具通过 Web Crypto API 使用加密安全随机性，确保每个结果真正不可预测和公平。您可以生成单个数字或一次批量生成数百个数字，并可选择按升序或降序排序结果。简洁的输出使您可以轻松复制单个数字或导出整个列表，用于电子表格、数据库或应用程序。无论您是在抽取竞赛获奖者、创建测试数据、为研究进行随机选择，还是构建需要公平随机性的游戏机制，此生成器都能提供可靠的结果。所有数字生成完全在浏览器本地使用安全的加密方法进行，意味着不会有任何随机种子或生成的值传输到外部服务器，使您的结果完全保持私密。`,
  },
  "image-to-pdf": {
    en: `Image to PDF converts your JPG, PNG, WebP, and other image formats into a polished PDF document in seconds. This essential tool is perfect for creating photo albums, submitting image-based documents, combining scanned pages into a single file, or preparing images for printing and archiving. Simply drag and drop one or more images, reorder them as needed, and download a perfectly formatted PDF. The tool maintains original image quality and aspect ratios while optimizing file size for efficient storage and sharing. You can customize the page orientation — portrait or landscape — and choose whether to fit images to page or preserve their original dimensions. The interface provides a thumbnail preview of your PDF before download so you can verify the layout. Whether you are compiling vacation photos into a shareable album, merging scanned receipts into one document for expense reports, or preparing image attachments for formal submissions, this tool handles it with ease. All image processing and PDF generation happens entirely in your browser — your images are never uploaded to any server, ensuring complete privacy.`,
    zh: `Image to PDF 可在几秒钟内将您的 JPG、PNG、WebP 和其他图像格式转换为精美的 PDF 文档。这款必备工具非常适合创建相册、提交基于图像的文件、将扫描页面合并为单个文件，或为打印和存档准备图像。只需拖放一张或多张图片，根据需要重新排序，然后下载格式完美的 PDF。该工具在保持原始图像质量和纵横比的同时优化文件大小，以实现高效存储和共享。您可以自定义页面方向——纵向或横向——并选择是将图像适配到页面还是保留其原始尺寸。该界面在下载前提供 PDF 缩略图预览，方便您验证布局。无论您是将度假照片编译成可分享的相册、将收据扫描件合并为费用报告的单个文档，还是为正式提交准备图像附件，此工具都能轻松处理。所有图像处理和 PDF 生成完全在浏览器中进行——您的图像永远不会上传到任何服务器，确保完全隐私。`,
  },
  "pdf-splitter": {
    en: `PDF Splitter allows you to easily extract specific pages or page ranges from any PDF document, creating separate smaller files from a single PDF. This indispensable tool is perfect for splitting chapter-based documents, extracting relevant sections from reports, separating invoices from a batch, or isolating specific pages for focused review. Upload your PDF and use the visual page thumbnail preview to select individual pages, entire ranges like pages 5 through 15, or use preset options for common splits like odd pages, even pages, or splitting in half. The tool displays clear page numbers and thumbnails so you can preview each page before selecting it. You can split a PDF into multiple parts in a single operation, with each extracted section downloading as a separate file. The process is intuitive and requires no technical knowledge. All PDF processing occurs entirely within your browser using client-side JavaScript — your document is never uploaded to any external server, making this a completely secure solution for splitting confidential, sensitive, or personal PDF files.`,
    zh: `PDF 分割器允许您轻松从任何 PDF 文档中提取特定页面或页面范围，从单个 PDF 创建单独的较小文件。这款不可或缺的工具非常适合分割按章节编排的文档、从报告中提取相关部分、从批量文件中分离发票，或隔离特定页面以进行重点审查。上传您的 PDF，使用可视化页面缩略图预览选择单个页面、完整范围（如第 5 到第 15 页），或使用常用分割预设（如奇数页、偶数页或对半分割）。该工具显示清晰的页码和缩略图，方便您在选择之前预览每个页面。您可以在一次操作中将 PDF 分割为多个部分，每个提取的部分作为单独文件下载。过程直观，无需任何技术知识。所有 PDF 处理完全在浏览器中使用客户端 JavaScript 进行——您的文档永远不会上传到任何外部服务器，使其成为分割机密、敏感或个人 PDF 文件的完全安全解决方案。`,
  },
  "pdf-rotator": {
    en: `PDF Rotator enables you to rotate pages in a PDF document by 90, 180, or 270 degrees to fix orientation issues in scanned documents, presentations, and digital forms. This practical tool is essential when you receive PDFs with sideways or upside-down pages from scanners, fax machines, or document digitization processes. Upload your PDF file and use the thumbnail preview to select which pages need rotation — you can rotate all pages at once or target specific pages individually. The tool shows a clear visual preview of each page before and after rotation so you can verify the orientation is correct before downloading. You can mix different rotation angles for different pages within the same document, providing complete flexibility for complex PDF files. The clean interface makes the rotation process straightforward even for non-technical users. All processing happens entirely in your browser using client-side PDF manipulation libraries — your document data never leaves your device, ensuring complete confidentiality for sensitive business documents, legal papers, and personal files.`,
    zh: `PDF 旋转器使您可以将 PDF 文档中的页面旋转 90、180 或 270 度，以修复扫描文档、演示文稿和数字表单中的方向问题。当您从扫描仪、传真机或文档数字化过程中收到页面横向或倒置的 PDF 时，这款实用工具必不可少。上传 PDF 文件，使用缩略图预览选择需要旋转的页面——您可以一次旋转所有页面，也可以单独针对特定页面。该工具在旋转前后显示每个页面的清晰视觉预览，方便您在下载前验证方向是否正确。您可以在同一文档中为不同页面混合不同的旋转角度，为复杂的 PDF 文件提供完全的灵活性。简洁的界面使旋转过程对非技术用户也简单明了。所有处理完全在浏览器中使用客户端 PDF 操作库进行——您的文档数据永远不会离开您的设备，确保敏感商业文件、法律文件和个人文件的完全保密性。`,
  },
  "pdf-page-remover": {
    en: `PDF Page Remover lets you quickly delete unwanted pages from your PDF documents, helping you trim down bloated files and keep only the content you need. This practical tool is perfect for removing blank pages from scanned documents, deleting irrelevant sections from reports, eliminating cover pages or appendices before sharing, and reducing file sizes for email attachments. Upload your PDF and browse through the visual page thumbnails to select which pages to remove. You can select individual pages, ranges, or use smart selection options to remove all blank pages at once. The tool provides a before-and-after page count so you can confirm exactly what will remain after deletion. Each selected page is clearly marked for easy verification. The process is simple, fast, and requires no software installation or technical expertise. All PDF processing takes place entirely within your browser using client-side technologies — your document never gets uploaded to any external server. This makes it completely safe for removing pages from confidential contracts, personal records, and sensitive business documents.`,
    zh: `PDF 页面删除器可让您快速从 PDF 文档中删除不需要的页面，帮助您精简臃肿的文件并仅保留所需内容。这款实用工具非常适合从扫描文档中删除空白页、从报告中删除不相关部分、在分享前删除封面页或附录，以及减小电子邮件附件的文件大小。上传 PDF，浏览视觉页面缩略图以选择要删除的页面。您可以选择单个页面、页面范围，或使用智能选择选项一次删除所有空白页。该工具提供删除前后的页数对比，方便您确认删除后将保留的确切内容。每个选定的页面都清晰标记，便于验证。过程简单快速，无需安装任何软件或技术专业知识。所有 PDF 处理完全在浏览器中使用客户端技术进行——您的文档永远不会上传到任何外部服务器。这使其完全安全，可用于从机密合同、个人记录和敏感商业文档中删除页面。`,
  },
  "image-cropper": {
    en: `Image Cropper is an intuitive, browser-based tool that lets you crop images to any size by simply dragging a selection area on the canvas. Perfect for social media posts, profile pictures, product photos, and design projects, this tool helps you remove unwanted backgrounds, focus on specific subjects, and achieve the exact dimensions you need. Upload any image and use the interactive crop frame to draw your desired area — resize and reposition it freely until you are satisfied. The tool displays real-time dimensions as you adjust the crop area, so you can match specific pixel or aspect ratio requirements with precision. You can lock the aspect ratio for consistent proportions or crop freely for custom sizes. Supports all common image formats including JPG, PNG, WebP, and GIF. The preview updates live as you drag, showing exactly what the final cropped image will look like. All cropping operations are performed entirely in your browser using the Canvas API — your image is never uploaded to any server, keeping your photos completely private and secure.`,
    zh: `Image Cropper 是一款直观的基于浏览器的工具，让您可以简单地在画布上拖动选择区域来将图像裁剪为任意大小。非常适合社交媒体帖子、个人头像、产品照片和设计项目，此工具帮助您移除不需要的背景、聚焦特定主体并获得所需的精确尺寸。上传任何图像，使用交互式裁剪框绘制您想要的区域——自由调整大小和位置直到满意为止。该工具在您调整裁剪区域时实时显示尺寸，方便您精确匹配特定像素或纵横比要求。您可以锁定纵横比以保持一致的比例，或自由裁剪以自定义大小。支持所有常见图像格式，包括 JPG、PNG、WebP 和 GIF。预览在拖动时实时更新，准确显示最终裁剪图像的样子。所有裁剪操作完全在浏览器中使用 Canvas API 进行——您的图像永远不会上传到任何服务器，使您的照片完全保持私密和安全。`,
  },
  "image-resizer": {
    en: `Image Resizer instantly scales your images to exact pixel dimensions while maintaining quality and aspect ratio control. This essential tool is invaluable for web developers optimizing images for faster page loads, social media managers preparing content for specific platform requirements, e-commerce sellers standardizing product photos, and designers meeting precise dimension specifications. Upload any image and enter your target width and height in pixels — the tool automatically maintains the aspect ratio by default to prevent distortion, or you can unlock it for custom non-proportional scaling. Choose your output format between JPG, PNG, and WebP, and adjust the compression quality to balance file size and visual fidelity. The live preview shows you exactly how the resized image will appear before you download. You can also use preset sizes for common use cases like social media banners, thumbnails, and featured images. All resizing computations happen locally in your browser using efficient Canvas processing, so your image data is never transmitted to external servers, ensuring complete privacy.`,
    zh: `Image Resizer 可即时将您的图像缩放到精确的像素尺寸，同时保持质量和纵横比控制。这款必备工具对于优化图像以加快页面加载速度的 Web 开发者、为特定平台要求准备内容的社交媒体经理、标准化产品照片的电子商务卖家，以及满足精确尺寸规格的设计师来说非常宝贵。上传任何图像并输入目标宽度和高度（以像素为单位）——该工具默认自动保持纵横比以防止失真，或您可以解锁它以进行自定义非等比缩放。在 JPG、PNG 和 WebP 之间选择输出格式，并调整压缩质量以平衡文件大小和视觉保真度。实时预览让您在下载前准确查看调整后的图像效果。您还可以使用常见用例的预设尺寸，如社交媒体横幅、缩略图和特色图片。所有缩放计算完全在浏览器本地使用高效的 Canvas 处理进行，因此您的图像数据永远不会传输到外部服务器，确保完全隐私。`,
  },
  "image-filters": {
    en: `Image Filters applies a rich collection of visual effects to your photos, including grayscale, sepia, blur, brightness, contrast, saturation, hue rotation, sharpen, invert, and many more artistic filters. This powerful browser-based editing tool lets you enhance and transform images without needing complex desktop software like Photoshop. Upload any image and browse through the filter gallery with live preview thumbnails showing each effect applied to your photo. Adjust filter intensity with simple sliders for fine-tuned control over each effect. You can combine multiple filters for unique looks, compare before and after views side by side, and fine-tune parameters like blur radius, brightness level, and contrast strength. When satisfied with your edited image, download it in your preferred format with quality settings. The tool supports JPG, PNG, and WebP output formats. Every filter operation runs entirely in your browser using Canvas and WebGL processing, meaning your images are never uploaded to any external server. This complete client-side processing guarantees that your personal photos and creative works remain private.`,
    zh: `Image Filters 为您的照片应用丰富的视觉效果集合，包括灰度、棕褐色、模糊、亮度、对比度、饱和度、色相旋转、锐化、反转以及更多艺术滤镜。这款功能强大的基于浏览器的编辑工具让您可以增强和变换图像，而无需复杂的桌面软件如 Photoshop。上传任何图像，浏览带有实时预览缩略图的滤镜库，查看每个效果应用于您照片的样子。使用简单滑块调整滤镜强度，对每个效果进行微调控制。您可以组合多个滤镜以获得独特效果，并排比较前后视图，微调模糊半径、亮度级别和对比度强度等参数。对编辑后的图像满意后，以首选格式和质量设置下载。该工具支持 JPG、PNG 和 WebP 输出格式。每个滤镜操作完全在浏览器中使用 Canvas 和 WebGL 处理运行，意味着您的图像永远不会上传到任何外部服务器。这种完全的客户端处理保证了您的个人照片和创意作品的隐私。`,
  },
  "color-picker": {
    en: `Color Picker from Image lets you extract exact color values from any uploaded image by simply clicking on the desired area, making it an indispensable tool for designers, developers, and digital artists. Upload a photo, screenshot, or design mockup and use the eyedropper cursor to pick any pixel's color — the tool instantly displays the corresponding HEX, RGB, and HSL color values for immediate use in your projects. The magnified preview helps you select precise pixels even in detailed images. You can pick multiple colors to build a palette directly from an image, copy any color code with one click, and see a history of your recent picks for easy reference. The tool also includes a standalone color selector for choosing custom colors without an image source. Whether you are matching brand colors from a logo, extracting a color scheme from a nature photograph for a design project, or finding the exact shade of a UI element, this tool delivers pixel-perfect accuracy. All color picking and image processing happens entirely in your browser — your images are never uploaded to any server, maintaining complete privacy.`,
    zh: `Color Picker from Image 让您通过简单点击所需区域从任何上传的图像中提取精确的颜色值，是设计师、开发者和数字艺术家不可或缺的工具。上传照片、截图或设计模型，使用吸管光标拾取任何像素的颜色——工具立即显示相应的 HEX、RGB 和 HSL 颜色值，可立即用于您的项目。放大预览帮助您即使在细节丰富的图像中也能选择精确的像素。您可以拾取多种颜色直接从图像构建调色板，一键复制任何颜色代码，并查看最近拾取的历史记录以便轻松参考。该工具还包含独立的颜色选择器，用于在没有图像来源的情况下选择自定义颜色。无论您是从 logo 匹配品牌颜色、从自然照片提取设计项目的配色方案，还是查找 UI 元素的确切色调，此工具都能提供像素级精确度。所有颜色拾取和图像处理完全在浏览器中进行——您的图像永远不会上传到任何服务器，保持完全隐私。`,
  },
  "gif-maker": {
    en: `GIF Maker transforms multiple images into smooth, animated GIF files that you can share on websites, social media, messaging apps, and presentations. This browser-based animation tool is perfect for creating simple animations, step-by-step tutorials, before-and-after comparisons, reaction GIFs, and fun custom stickers. Upload two or more images — supporting JPG, PNG, WebP, and even other GIFs — then arrange them in your desired sequence using drag-and-drop reordering. Adjust the frame delay to control animation speed, set the output dimensions for optimal file size, and enable or disable looping. The tool provides a real-time preview of your animated GIF before download, so you can verify the timing and sequence are exactly right. You can also add frames from existing GIFs to remix and create new animations. When satisfied, download your GIF with a single click. All image processing and GIF encoding happens locally in your browser using the Canvas API and client-side encoding — your images and resulting GIF are never uploaded to any server, ensuring complete privacy for your creative content.`,
    zh: `GIF Maker 将多张图像转换为流畅的动画 GIF 文件，您可以将其分享到网站、社交媒体、消息应用和演示文稿中。这款基于浏览器的动画工具非常适合创建简单动画、分步教程、前后对比、反应 GIF 和有趣的自定义贴纸。上传两张或更多图像——支持 JPG、PNG、WebP，甚至其他 GIF——然后使用拖放重新排序按所需顺序排列它们。调整帧延迟以控制动画速度，设置输出尺寸以获得最佳文件大小，并启用或禁用循环。该工具在下载前提供动画 GIF 的实时预览，方便您验证时间和顺序是否完全正确。您还可以从现有 GIF 中添加帧以重新混搭并创建新动画。满意后，一键下载您的 GIF。所有图像处理和 GIF 编码完全在浏览器中使用 Canvas API 和客户端编码进行——您的图像和生成的 GIF 永远不会上传到任何服务器，确保您创意内容的完全隐私。`,
  },
  "image-watermark": {
    en: `Image Watermark adds customizable text watermarks to your photos to protect intellectual property, brand your images, and claim ownership of your visual content. This essential tool for photographers, content creators, and businesses lets you overlay text with full control over font, size, color, opacity, position, and rotation. Upload any image and type your watermark text — choose from built-in fonts, adjust the text color to complement or contrast with your photo, set the transparency level so the watermark is visible yet non-intrusive, and position it anywhere on the image using click-and-drag. The tool supports multiple watermarks per image, so you can add both a name and a date or create a repeating pattern. Live preview shows the watermark effect in real time as you make adjustments. When satisfied, download the watermarked image in your preferred format. All watermarking operations are performed entirely in your browser using Canvas processing — your photos are never uploaded to any server, ensuring complete privacy and control over your valuable visual assets.`,
    zh: `Image Watermark 为您的照片添加可自定义的文字水印，以保护知识产权、为图片打上品牌标记并声明您视觉内容的所有权。这款对于摄影师、内容创作者和企业来说必不可少的工具，让您完全控制字体、大小、颜色、透明度、位置和旋转来叠加文字。上传任何图像并输入您的水印文本——从内置字体中选择，调整文字颜色以与照片协调或形成对比，设置透明度使水印可见但不干扰，并使用点击拖放将其放置在图像上的任何位置。该工具支持每张图像多个水印，因此您可以同时添加名称和日期，或创建重复图案。实时预览在您调整时即时显示水印效果。满意后，以首选格式下载带水印的图像。所有水印操作完全在浏览器中使用 Canvas 处理进行——您的照片永远不会上传到任何服务器，确保对您宝贵视觉资产的完全隐私和控制。`,
  },
  "image-merge": {
    en: `Image Merger combines multiple images into a single composite image using flexible grid layouts, side-by-side arrangements, or custom positioning. This versatile tool is perfect for creating photo comparisons, before-and-after montages, mood boards, contact sheets, and multi-image collages for presentations and social media. Upload two or more images and choose from several merge modes: place images side by side horizontally, stack them vertically, arrange them in a grid with configurable rows and columns, or use free positioning for custom layouts. The tool automatically adjusts spacing between images, allows background color customization, and lets you set the final output dimensions. A live preview shows the merged result in real time as you rearrange and add images. Drag and drop to reorder, remove individual images, or add more at any time. Download the merged image in JPG, PNG, or WebP format. All image merging happens locally in your browser using Canvas APIs — your photos are never sent to any external server, making this a completely private solution for combining personal or professional images.`,
    zh: `Image Merger 使用灵活的网格布局、并排排列或自定义定位将多张图像组合为单张合成图像。这款多功能工具非常适合创建照片对比、前后对比蒙太奇、情绪板、联系表和用于演示文稿及社交媒体的多图拼贴。上传两张或更多图像，从多种合并模式中选择：水平并排放置图像、垂直堆叠、以可配置的行和列排列在网格中，或使用自由定位进行自定义布局。该工具自动调整图像之间的间距，允许自定义背景颜色，并可设置最终输出尺寸。实时预览在您重新排列和添加图像时即时显示合并结果。拖放以重新排序，移除单个图像，或随时添加更多图像。以 JPG、PNG 或 WebP 格式下载合并后的图像。所有图像合并完全在浏览器中使用 Canvas API 进行——您的照片永远不会发送到任何外部服务器，使其成为组合个人或专业图像的完全私密解决方案。`,
  },
  "image-splitter": {
    en: `Image Splitter divides a single image into multiple tiles by rows and columns, creating perfectly equal segments ideal for social media puzzles, sprite sheets, game assets, and grid-based designs. Upload any image and specify how many rows and columns you want — the tool calculates and displays each tile's dimensions automatically. Use it to split images into a 3x3 Instagram grid, create equal segments for before-and-after comparisons, generate sprite sheet tiles for game development, or produce image puzzles for marketing campaigns. The visual preview shows exactly how your image will be divided with grid overlay lines, so you can verify the layout before downloading. Each tile is numbered for easy identification and assembly. You can download all tiles as individual files in a single action or select specific tiles to download separately. Supports all common image formats including JPG, PNG, WebP, and GIF. All splitting operations occur entirely in your browser using client-side Canvas processing — your original image and all generated tiles never leave your device, ensuring complete privacy.`,
    zh: `Image Splitter 通过行和列将单张图像分割成多个图块，创建完美均等的片段，非常适合社交媒体拼图、精灵表、游戏素材和基于网格的设计。上传任何图像并指定所需的行数和列数——工具自动计算并显示每个图块的尺寸。使用它将图像分割为 3x3 Instagram 网格、为前后对比创建均等片段、为游戏开发生成精灵表图块，或为营销活动制作图像拼图。视觉预览使用网格叠加线准确显示图像将如何被分割，方便您在下载前验证布局。每个图块都编号以便于识别和组装。您可以一次操作下载所有图块为单个文件，或选择特定图块单独下载。支持所有常见图像格式，包括 JPG、PNG、WebP 和 GIF。所有分割操作完全在浏览器中使用客户端 Canvas 处理进行——您的原始图像和所有生成的图块永远不会离开您的设备，确保完全隐私。`,
  },
  "image-flip": {
    en: `Image Flip and Rotate is a quick and precise tool for flipping images horizontally or vertically and rotating them by 90-degree increments. This essential image editing utility is perfect for correcting mirrored selfies, fixing upside-down scanned documents, creating symmetric design effects, and adjusting photo orientation for social media platforms. Upload any image and use the one-click buttons to flip it horizontally for a mirror effect, flip vertically to correct top-bottom orientation, or rotate clockwise and counterclockwise in 90-degree steps. The tool provides a live preview that updates instantly as you apply each transformation, so you can see the result before downloading. You can apply multiple transformations in sequence to achieve the exact orientation you need — for example, flip horizontally and then rotate 180 degrees for a specific effect. The clean interface requires no image editing experience to use effectively. All transformations are processed locally in your browser using Canvas API — your images are never uploaded to any external server, keeping your photos completely private and secure.`,
    zh: `Image Flip and Rotate 是一款快速精确的工具，用于水平或垂直翻转图像以及按 90 度增量旋转图像。这款必备图像编辑实用工具非常适合修正镜像自拍、修复倒置的扫描文档、创建对称设计效果以及调整社交媒体平台的照片方向。上传任何图像，使用一键按钮将其水平翻转以获得镜像效果、垂直翻转以修正上下方向，或顺时针和逆时针以 90 度步长旋转。该工具提供实时预览，应用每个变换时即时更新，方便您在下载前查看结果。您可以按顺序应用多个变换以获得所需的精确方向——例如，先水平翻转然后旋转 180 度以获得特定效果。简洁的界面无需图像编辑经验即可有效使用。所有变换完全在浏览器中使用 Canvas API 处理——您的图像永远不会上传到任何外部服务器，使您的照片完全保持私密和安全。`,
  },
  "image-border": {
    en: `Image Border adds professional borders, frames, and padding to your images with full control over width, color, corner radius, and shadow effects. This design-focused tool is perfect for creating polished photos for social media, product listings, presentations, and digital galleries. Upload any image and customize your border — choose from solid colors, set the border width in pixels, adjust corner rounding for smooth or sharp edges, and add drop shadows for depth and dimension. The tool provides real-time preview so you can see every change as you make it, from a thin elegant frame to a thick bold border. You can add inner padding between the image and the border for a matted photo effect, perfect for showcasing artwork and portraits. Adjust the shadow offset, blur radius, and color to create professional-looking depth. Choose between JPG, PNG, and WebP output formats depending on your needs. All border rendering and image processing happens entirely in your browser using Canvas — your images are never transmitted to any server, guaranteeing complete privacy for your personal and professional photos.`,
    zh: `Image Border 为您的图像添加专业边框、框架和内边距，完全控制宽度、颜色、圆角和阴影效果。这款专注于设计的工具非常适合为社交媒体、产品列表、演示文稿和数字画廊创建精致的照片。上传任何图像并自定义边框——选择纯色、以像素为单位设置边框宽度、调整角部圆滑度以获得平滑或尖锐的边缘，并添加投影以增加深度和层次感。该工具提供实时预览，方便您在制作时查看每个更改，从优雅的细边框到大胆的粗边框。您可以在图像和边框之间添加内边距以获得衬裱照片效果，非常适合展示艺术品和肖像。调整投影偏移、模糊半径和颜色以创建专业外观的深度感。根据需要在 JPG、PNG 和 WebP 输出格式之间选择。所有边框渲染和图像处理完全在浏览器中使用 Canvas 进行——您的图像永远不会传输到任何服务器，保证您个人和专业照片的完全隐私。`,
  },
  "meme-generator": {
    en: `Meme Generator lets you create hilarious memes by adding bold top and bottom text to any image, making it the go-to tool for social media humor, viral content creation, and online entertainment. Upload any photo — whether it is a reaction shot, a cute animal, a movie still, or your own picture — and type your custom top and bottom text in the classic meme format. The tool automatically applies the signature Impact-style bold white text with black outline that defines internet meme culture, and you can customize font size, text color, outline color, and positioning. The live preview shows your meme in real time as you type, letting you fine-tune the text placement for maximum comedic impact. You can upload your own images or use any picture you have on hand. Download your finished meme as a high-quality JPG or PNG image ready to share on any social media platform, messaging app, or forum. All image processing and text overlay happens entirely in your browser — your images and created memes never leave your device, ensuring complete privacy.`,
    zh: `Meme Generator 让您通过在任何图像上添加醒目的顶部和底部文本来创建有趣的表情包，使其成为社交媒体幽默、病毒式内容创作和在线娱乐的首选工具。上传任何照片——无论是反应镜头、可爱动物、电影截图还是您自己的图片——然后以经典表情包格式输入自定义顶部和底部文本。该工具自动应用定义互联网表情包文化的标志性 Impact 风格粗体白色文本加黑色轮廓，您还可以自定义字体大小、文本颜色、轮廓颜色和位置。实时预览在您输入时即时显示您的表情包，方便您微调文本位置以获得最大的喜剧效果。您可以上传自己的图片或使用手头的任何图片。将完成的表情包下载为高质量的 JPG 或 PNG 图像，可直接分享到任何社交媒体平台、消息应用或论坛。所有图像处理和文本叠加完全在浏览器中进行——您的图像和创建的表情包永远不会离开您的设备，确保完全隐私。`,
  },
  "image-to-sketch": {
    en: `Image to Sketch transforms your photographs into realistic pencil sketch drawings and line art using advanced browser-based image processing algorithms. This creative tool is perfect for artists seeking inspiration, designers creating hand-drawn style mockups, and anyone who wants to give their photos an artistic makeover. Upload any image and the tool applies an edge-detection algorithm that identifies contours, outlines, and details to produce a convincing pencil sketch effect. You can adjust the sketch intensity, contrast, and detail level to achieve anything from a light, subtle drawing to a bold, high-contrast line art piece. The tool also supports inverted sketch mode for dark backgrounds and different pencil hardness effects. A side-by-side preview lets you compare the original photo with the sketch result in real time. Download your sketch as a JPG or PNG file suitable for printing, framing, or digital sharing. All image processing happens entirely in your browser using Canvas-based algorithms — your photographs are never uploaded to any external server, keeping your personal images completely private.`,
    zh: `Image to Sketch 使用先进的基于浏览器的图像处理算法将您的照片转换为逼真的铅笔素描和线稿。这款创意工具非常适合寻求灵感的艺术家、创建手绘风格模型的设计师，以及任何想要给照片艺术感的人。上传任何图像，工具应用边缘检测算法来识别轮廓、边界线和细节，以产生令人信服的铅笔素描效果。您可以调整素描强度、对比度和细节级别，实现从轻柔微妙的绘图到大胆高对比度的线稿作品。该工具还支持深色背景的反转素描模式和不同的铅笔硬度效果。并排预览让您实时比较原始照片和素描结果。将素描下载为适合打印、装裱或数字分享的 JPG 或 PNG 文件。所有图像处理完全在浏览器中使用基于 Canvas 的算法进行——您的照片永远不会上传到任何外部服务器，使您的个人图像完全保持私密。`,
  },
  "emoji-remover": {
    en: `Emoji Remover instantly strips all emoji characters from your text while preserving regular words, numbers, and punctuation. This practical text utility is essential for cleaning up social media content, preparing text for databases that do not support emoji, sanitizing input for technical systems, and ensuring compatibility with legacy applications. Simply paste your text into the input field and the tool immediately removes all emoji characters, displaying the cleaned text alongside a count of removed emojis. It handles all emoji types including skin tone modifiers, flag emojis, compound emoji sequences, and zero-width joiner combinations that form complex emoji characters. The tool also preserves all other Unicode text including accented characters, non-Latin scripts, and special symbols that are not emoji. You can copy the cleaned output with one click for immediate use elsewhere. All processing happens locally in your browser — your text data is never transmitted to any server, ensuring complete privacy for sensitive documents, personal messages, or any text content you need to clean.`,
    zh: `Emoji Remover 可即时从您的文本中清除所有表情符号字符，同时保留普通文字、数字和标点符号。这款实用的文本工具对于清理社交媒体内容、为不支持表情符号的数据库准备文本、为技术系统清理输入以及确保与旧版应用程序的兼容性至关重要。只需将文本粘贴到输入框中，工具即立即移除所有表情符号字符，并在旁边显示清理后的文本和已移除表情符号的计数。它处理所有表情符号类型，包括肤色修饰符、国旗表情符号、复合表情符号序列和形成复杂表情符号的零宽连接符组合。该工具还保留所有其他 Unicode 文本，包括重音字符、非拉丁文脚本和非表情符号的特殊符号。您可以一键复制清理后的输出，方便立即在其他地方使用。所有处理完全在浏览器本地进行——您的文本数据永远不会传输到任何服务器，确保敏感文档、个人消息或任何需要清理的文本内容的完全隐私。`,
  },
  "unicode-detector": {
    en: `Unicode Character Detector inspects any text and provides detailed information about each Unicode character, including its code point, character category, name, and encoding details. This indispensable developer and linguist tool helps you understand mysterious or unknown characters, debug encoding issues, identify invisible characters like zero-width spaces, and verify proper Unicode compliance in your text. Simply paste or type any text and the tool analyzes it character by character, displaying each character's Unicode code point (like U+0041), official Unicode name (like LATIN CAPITAL LETTER A), general category (like Letter, uppercase), and block information. It highlights special characters such as combining marks, control characters, and directional indicators that may cause unexpected behavior in applications. The tool supports all Unicode planes including emoji, mathematical symbols, and historical scripts. You can click on any detected character to see its full Unicode profile. All analysis is performed locally in your browser — your text data never leaves your device, ensuring complete privacy for examining sensitive documents or proprietary content.`,
    zh: `Unicode 字符检测器检查任何文本并提供每个 Unicode 字符的详细信息，包括其码位、字符类别、名称和编码详情。这款对开发者和语言学家不可或缺的工具帮助您理解神秘或未知字符、调试编码问题、识别零宽空格等不可见字符，以及验证文本中的正确 Unicode 合规性。只需粘贴或输入任何文本，工具即逐字符分析，显示每个字符的 Unicode 码位（如 U+0041）、官方 Unicode 名称（如 LATIN CAPITAL LETTER A）、通用类别（如 Letter, uppercase）和区块信息。它突出显示组合标记、控制字符和方向指示符等特殊字符，这些字符可能导致应用程序中的意外行为。该工具支持所有 Unicode 平面，包括表情符号、数学符号和历史脚本。您可以点击任何检测到的字符查看其完整的 Unicode 档案。所有分析完全在浏览器本地进行——您的文本数据永远不会离开您的设备，确保检查敏感文档或专有内容时的完全隐私。`,
  },
  "caesar-cipher": {
    en: `Caesar Cipher encodes and decodes text using the classic Caesar shift cipher, one of the oldest and simplest encryption methods in cryptographic history. This educational and fun tool lets you choose any shift value from 1 to 25 to encrypt your message, or try brute force mode to automatically test all 25 possible shifts to decode an unknown cipher. Simply enter your plaintext and select a shift value to see the encoded result instantly, or paste a ciphertext and let the tool reveal the original message. The tool supports both uppercase and lowercase letters while preserving numbers, spaces, and punctuation unchanged. It displays the Caesar cipher alphabet reference so you can learn how each letter maps to its shifted counterpart. Perfect for cryptography students, puzzle enthusiasts, game developers creating coded messages, and teachers demonstrating basic encryption concepts. All encoding and decoding operations occur entirely in your browser — no text data is ever sent to any server, ensuring complete privacy for your secret messages.`,
    zh: `Caesar Cipher 使用经典的凯撒移位密码对文本进行编码和解码，这是密码学历史上最古老、最简单的加密方法之一。这款教育性和趣味性兼备的工具让您选择 1 到 25 之间的任何移位值来加密消息，或尝试暴力破解模式自动测试所有 25 种可能的移位来解码未知密文。只需输入明文并选择移位值即可即时查看编码结果，或粘贴密文让工具揭示原始消息。该工具支持大写和小写字母，同时保持数字、空格和标点符号不变。它显示凯撒密码字母表参考，方便您学习每个字母如何映射到其移位后的对应字母。非常适合密码学学生、谜题爱好者、创建编码消息的游戏开发者，以及演示基本加密概念的教师。所有编码和解码操作完全在浏览器中进行——不会有任何文本数据发送到任何服务器，确保您秘密消息的完全隐私。`,
  },
  "json-diff": {
    en: `JSON Diff compares two JSON objects side by side and highlights every difference, making it an essential debugging and configuration management tool for developers. Whether you are comparing API responses, checking configuration file changes, reviewing database exports, or debugging data synchronization issues, this tool provides instant visual feedback on what has changed between two JSON structures. Paste your original JSON on the left and the modified version on the right, and the tool immediately identifies and color-codes additions, deletions, and modifications at every level of the object hierarchy. It handles nested objects, arrays, different data types, and deeply complex JSON structures with precision. Added keys are highlighted in green, removed keys in red, and modified values in yellow for instant visual clarity. The tool also shows the path to each difference, making it easy to locate changes in large JSON documents. All comparison processing happens entirely in your browser using efficient JavaScript algorithms — your JSON data is never transmitted to any external server, ensuring complete confidentiality for sensitive API payloads and configuration data.`,
    zh: `JSON Diff 并排比较两个 JSON 对象并突出显示每个差异，是开发者的必备调试和配置管理工具。无论您是比较 API 响应、检查配置文件更改、审查数据库导出还是调试数据同步问题，此工具都能即时提供两个 JSON 结构之间变化的视觉反馈。将原始 JSON 粘贴在左侧，修改版本粘贴在右侧，工具立即在对象层级的每一级识别并用颜色编码标记添加、删除和修改。它精确处理嵌套对象、数组、不同数据类型和深度复杂的 JSON 结构。添加的键用绿色突出显示，删除的键用红色，修改的值用黄色，实现即时视觉清晰度。该工具还显示每个差异的路径，方便在大型 JSON 文档中定位更改。所有比较处理完全在浏览器中使用高效的 JavaScript 算法进行——您的 JSON 数据永远不会传输到任何外部服务器，确保敏感 API 负载和配置数据的完全保密性。`,
  },
  "http-status-codes": {
    en: `HTTP Status Codes is a comprehensive, searchable reference guide that lists all standard HTTP response codes with detailed descriptions, common causes, and practical solutions. This essential web developer tool helps you quickly understand and troubleshoot any HTTP error or response you encounter while building, testing, or debugging web applications and APIs. Browse codes organized by category — informational (1xx), success (2xx), redirection (3xx), client errors (4xx), and server errors (5xx) — or use the search function to jump directly to a specific code like 404, 500, or 429. Each status code entry includes its official name, a clear explanation of what it means, typical scenarios when you would see it, and recommended actions to resolve the issue. The tool covers all standard codes defined in the HTTP specification as well as commonly used unofficial codes. Whether you are a junior developer learning about REST APIs, a DevOps engineer debugging production issues, or a student studying web protocols, this reference provides clear, accurate information. All content is loaded and rendered entirely in your browser with no external data requests, ensuring a fast, private browsing experience.`,
    zh: `HTTP 状态码是一款全面的、可搜索的参考指南，列出所有标准 HTTP 响应代码及其详细描述、常见原因和实用解决方案。这款必备的 Web 开发者工具帮助您在构建、测试或调试 Web 应用和 API 时快速理解并排除遇到的任何 HTTP 错误或响应。按类别浏览代码——信息性（1xx）、成功（2xx）、重定向（3xx）、客户端错误（4xx）和服务器错误（5xx）——或使用搜索功能直接跳转到特定代码，如 404、500 或 429。每个状态码条目包括其官方名称、清晰的含义说明、您可能遇到它的典型场景，以及解决该问题的推荐操作。该工具涵盖 HTTP 规范中定义的所有标准代码以及常用的非官方代码。无论您是学习 REST API 的初级开发者、调试生产问题的 DevOps 工程师，还是学习 Web 协议的学生，此参考都能提供清晰准确的信息。所有内容完全在浏览器中加载和渲染，无需外部数据请求，确保快速私密的浏览体验。`,
  },
};
