import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Frequently Asked Questions — ToolboxPro",
  description:
    "Answers to common questions about ToolboxPro free online tools. Privacy, features, file limits, and more.",
  alternates: {
    canonical: "https://trytoolboxpro.com/faq",
  },
};

const faqs = [
  {
    q: "Is ToolboxPro really free?",
    a: "Yes, ToolboxPro is 100% free with no hidden charges. There are no premium tiers, no watermarks, and no usage limits. You can use all 99 tools as many times as you want.",
  },
  {
    q: "Do I need to create an account?",
    a: "No. ToolboxPro requires no signup, no email, and no password. Just open a tool and start using it immediately.",
  },
  {
    q: "Are my files uploaded to a server?",
    a: "No. All processing happens locally in your browser using JavaScript, Canvas, and WebAssembly. Your files never leave your device — making ToolboxPro safe for sensitive documents.",
  },
  {
    q: "What file formats are supported?",
    a: "ToolboxPro supports a wide range of formats including JPEG, PNG, WebP, GIF, BMP (images), PDF (documents), MP3, WAV, OGG (audio), JSON, CSV, HTML, and many text formats. Check each tool's page for specific format support.",
  },
  {
    q: "Is there a file size limit?",
    a: "There's no artificial limit imposed by ToolboxPro. The practical limit is your browser's available memory. For images, files up to 50MB work well. For PDFs, up to 100MB. For text, up to 100,000 characters.",
  },
  {
    q: "Does it work on mobile?",
    a: "Yes. All ToolboxPro tools are designed to work on both desktop and mobile browsers. The responsive layout adapts to any screen size.",
  },
  {
    q: "How do I report a bug or request a feature?",
    a: "Visit our Contact page or email hyehugh520@gmail.com. We respond to all feedback and regularly add new tools based on user requests.",
  },
  {
    q: "Can I use ToolboxPro tools for commercial purposes?",
    a: "Yes. All tools are free for both personal and commercial use. There are no restrictions on how you use the output generated by our tools.",
  },
  {
    q: "Why should I use client-side tools instead of server-side alternatives?",
    a: "Client-side tools offer three key advantages: (1) Privacy — your data never leaves your device, (2) Speed — no upload/download wait time, (3) Reliability — works offline after first load. Server-side tools require uploading sensitive files to unknown servers.",
  },
  {
    q: "How often are new tools added?",
    a: "We regularly add new tools based on user requests and market needs. Follow our Blog or check the All Tools page to see the latest additions.",
  },
  {
    q: "What browsers are supported?",
    a: "ToolboxPro works on all modern browsers including Chrome, Firefox, Safari, Edge, and their mobile versions. We recommend keeping your browser updated for the best experience.",
  },
  {
    q: "Is the code open source?",
    a: "The source code is available on GitHub. Check the footer of any page for the repository link.",
  },
];

const faqPageSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.q,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.a,
    },
  })),
};

export default function FAQPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqPageSchema) }}
      />
      <div className="mx-auto max-w-3xl px-4 py-12">
        <div className="mb-10">
          <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-3">
            Frequently Asked Questions
          </h1>
          <p className="text-lg text-muted-foreground max-w-2xl">
            Answers to common questions about ToolboxPro — our free online tools, privacy
            approach, and how everything works.
          </p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, i) => (
            <details
              key={i}
              className="group rounded-xl border bg-card p-5 [&_summary]:cursor-pointer [&_summary]:font-medium [&_summary]:flex [&_summary]:items-center [&_summary]:justify-between [&_summary]:gap-4"
            >
              <summary className="list-none">
                <span>{faq.q}</span>
                <span className="flex-shrink-0 transition-transform group-open:rotate-180 text-muted-foreground">
                  ▼
                </span>
              </summary>
              <p className="mt-3 text-muted-foreground leading-relaxed">{faq.a}</p>
            </details>
          ))}
        </div>

        <div className="mt-12 p-6 rounded-xl border bg-card/50 text-center">
          <p className="text-muted-foreground mb-4">
            Still have questions? We&apos;re here to help.
          </p>
          <Link
            href="/contact"
            className="inline-flex items-center px-6 py-3 rounded-lg bg-primary text-primary-foreground font-medium hover:bg-primary/90 transition-colors"
          >
            Contact Us
          </Link>
        </div>
      </div>
    </>
  );
}
